use std::sync::OnceLock;

#[cfg(test)]
use jellium_model::construct::Sentence;

/// Declares the text enum, the roll the gate reads and the key each variant
/// reads under, from one list. A variant named here is in all three; a variant
/// named nowhere else does not exist.
macro_rules! text {
    ($($variant:ident => $key:literal, $wording:expr,)*) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Text {
            $($variant,)*
        }

        impl Text {
            /// Every variant, which is what the string table is checked
            /// against.
            #[cfg(test)]
            pub const ALL: &'static [Text] = &[$(Text::$variant,)*];

            /// The key this text reads under in the string table.
            pub fn key(self) -> &'static str {
                match self {
                    $(Text::$variant => $key,)*
                }
            }

            /// Read by the construct gate out of this file's own `text!`
            /// list, and by nothing at runtime, so it stands under
            /// `#[cfg(test)]` beside `ALL`, `BOOT_KEYS` and `written`.
            /// `cargo clippy --all-targets` and `cargo test` both build it, so
            /// every `Sentence` path in the list is type-checked on every run
            /// of the build.
            #[cfg(test)]
            pub fn sentence(self) -> Wording {
                match self {
                    $(Text::$variant => $wording,)*
                }
            }
        }
    };
}

/// Which key of the reference's own string table a sentence of this client
/// carries.
#[cfg(test)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Wording {
    /// The key `reference/constructs.tsv` gives the construct this sentence is
    /// drawn under.
    Reference(Sentence),
    /// No construct of that table keys this sentence. This is a fact about the
    /// table and not a claim that the sentence is this client's own; own-ness
    /// is asserted by a row of `reference/exemptions.tsv` and nowhere else.
    Unkeyed,
}

text! {
    SetupTitle => "setupTitle", Wording::Unkeyed,
    SetupPosition => "setupPosition", Wording::Unkeyed,
    SetupNext => "setupNext", Wording::Unkeyed,
    SetupBack => "setupBack", Wording::Unkeyed,
    SetupResumed => "setupResumed", Wording::Unkeyed,
    SetupLanguage => "setupLanguage", Wording::Unkeyed,
    SetupLanguageCulture => "setupLanguageCulture", Wording::Unkeyed,
    SetupLanguageServerName => "setupLanguageServerName", Wording::Unkeyed,
    SetupLanguageScope => "setupLanguageScope", Wording::Unkeyed,
    SetupUser => "setupUser", Wording::Unkeyed,
    SetupUserName => "setupUserName", Wording::Unkeyed,
    SetupUserPassword => "setupUserPassword", Wording::Unkeyed,
    SetupUserConfirm => "setupUserConfirm", Wording::Unkeyed,
    SetupUserMismatch => "setupUserMismatch", Wording::Unkeyed,
    SetupLibraries => "setupLibraries", Wording::Unkeyed,
    SetupLibrariesEmpty => "setupLibrariesEmpty", Wording::Unkeyed,
    SetupLibrariesAdd => "setupLibrariesAdd", Wording::Unkeyed,
    SetupLibrariesCancel => "setupLibrariesCancel", Wording::Unkeyed,
    SetupLibrariesUp => "setupLibrariesUp", Wording::Unkeyed,
    SetupMetadata => "setupMetadata", Wording::Unkeyed,
    SetupMetadataLanguage => "setupMetadataLanguage", Wording::Unkeyed,
    SetupMetadataCountry => "setupMetadataCountry", Wording::Unkeyed,
    SetupRemoteAccess => "setupRemoteAccess", Wording::Unkeyed,
    SetupRemoteAccessEnable => "setupRemoteAccessEnable", Wording::Unkeyed,
    SetupRemoteAccessPortMapping => "setupRemoteAccessPortMapping", Wording::Unkeyed,
    SetupFinish => "setupFinish", Wording::Unkeyed,
    SetupFinishMessage => "setupFinishMessage", Wording::Unkeyed,
    SetupFinishAction => "setupFinishAction", Wording::Unkeyed,
    LibrariesContentMovies => "librariesContentMovies", Wording::Unkeyed,
    LibrariesContentShows => "librariesContentShows", Wording::Unkeyed,
    LibrariesContentMusic => "librariesContentMusic", Wording::Unkeyed,
    LibrariesContentMusicVideos => "librariesContentMusicVideos", Wording::Unkeyed,
    LibrariesContentHomeVideos => "librariesContentHomeVideos", Wording::Unkeyed,
    LibrariesContentCollections => "librariesContentCollections", Wording::Unkeyed,
    LibrariesContentBooks => "librariesContentBooks", Wording::Unkeyed,
    LibrariesContentMixed => "librariesContentMixed", Wording::Unkeyed,
    LibrariesContentOther => "librariesContentOther", Wording::Unkeyed,
    FailureSetupReadOnly => "failureSetupReadOnly", Wording::Unkeyed,
    FailureSetupFinished => "failureSetupFinished", Wording::Unkeyed,
    FailureSetupSignIn => "failureSetupSignIn", Wording::Unkeyed,
    FailureStageSetupOnly => "failureStageSetupOnly", Wording::Unkeyed,
    FailureStageSignedOnly => "failureStageSignedOnly", Wording::Unkeyed,
    FailureWroteSetupStep => "failureWroteSetupStep", Wording::Unkeyed,
    AppName => "appName", Wording::Unkeyed,
    BootNoBackend => "bootNoBackend", Wording::Unkeyed,
    BootNoViewport => "bootNoViewport", Wording::Unkeyed,
    BootPanicked => "bootPanicked", Wording::Unkeyed,
    LoginHeader => "loginHeader", Wording::Unkeyed,
    LoginUsername => "loginUsername", Wording::Unkeyed,
    LoginPassword => "loginPassword", Wording::Unkeyed,
    LoginSubmit => "loginSubmit", Wording::Unkeyed,
    LoginWorking => "loginWorking", Wording::Unkeyed,
    LoginManual => "loginManual", Wording::Unkeyed,
    LoginCancel => "loginCancel", Wording::Unkeyed,
    NavSwitch => "navSwitch", Wording::Reference(Sentence::SelectServer),
    LoginServersTitle => "loginServersTitle", Wording::Unkeyed,
    LoginServersActive => "loginServersActive", Wording::Unkeyed,
    LoginServersSignedIn => "loginServersSignedIn", Wording::Unkeyed,
    LoginServersRemove => "loginServersRemove", Wording::Unkeyed,
    LoginServersAdd => "loginServersAdd", Wording::Unkeyed,
    LoginAddTitle => "loginAddTitle", Wording::Unkeyed,
    LoginAddUrl => "loginAddUrl", Wording::Unkeyed,
    LoginAddUrlHelp => "loginAddUrlHelp", Wording::Unkeyed,
    LoginAddSubmit => "loginAddSubmit", Wording::Unkeyed,
    LoginAddWorking => "loginAddWorking", Wording::Unkeyed,
    LoginBack => "loginBack", Wording::Unkeyed,
    LoginQuickConnect => "loginQuickConnect", Wording::Unkeyed,
    LoginQuickConnectTitle => "loginQuickConnectTitle", Wording::Unkeyed,
    LoginQuickConnectInstruction => "loginQuickConnectInstruction", Wording::Unkeyed,
    LoginQuickConnectCode => "loginQuickConnectCode", Wording::Unkeyed,
    LoginQuickConnectWaiting => "loginQuickConnectWaiting", Wording::Unkeyed,
    LoginQuickConnectRetry => "loginQuickConnectRetry", Wording::Unkeyed,
    LoginForgotPassword => "loginForgotPassword", Wording::Unkeyed,
    LoginResetTitle => "loginResetTitle", Wording::Unkeyed,
    LoginResetUsername => "loginResetUsername", Wording::Unkeyed,
    LoginResetHelp => "loginResetHelp", Wording::Unkeyed,
    LoginResetSubmit => "loginResetSubmit", Wording::Unkeyed,
    LoginResetPinWritten => "loginResetPinWritten", Wording::Unkeyed,
    LoginResetPinFile => "loginResetPinFile", Wording::Unkeyed,
    LoginResetExpires => "loginResetExpires", Wording::Unkeyed,
    LoginResetPin => "loginResetPin", Wording::Unkeyed,
    LoginResetPinSubmit => "loginResetPinSubmit", Wording::Unkeyed,
    LoginResetContactAdministrator => "loginResetContactAdministrator", Wording::Unkeyed,
    LoginResetInNetwork => "loginResetInNetwork", Wording::Unkeyed,
    LoginResetCleared => "loginResetCleared", Wording::Unkeyed,
    FailureThrew => "failureThrew", Wording::Unkeyed,
    FailureFontCoverage => "failureFontCoverage", Wording::Unkeyed,
    FailureFontFamily => "failureFontFamily", Wording::Unkeyed,
    FailureFontUnpacked => "failureFontUnpacked", Wording::Unkeyed,
    FailureFontUnread => "failureFontUnread", Wording::Unkeyed,
    FailureStored => "failureStored", Wording::Unkeyed,
    FailureTouchPoints => "failureTouchPoints", Wording::Unkeyed,
    FailureScreenSize => "failureScreenSize", Wording::Unkeyed,
    FailureSpeakerCount => "failureSpeakerCount", Wording::Unkeyed,
    FailureFullscreen => "failureFullscreen", Wording::Unkeyed,
    FailureBeacon => "failureBeacon", Wording::Unkeyed,
    FailureLiveNoUrl => "failureLiveNoUrl", Wording::Unkeyed,
    FailureLiveNoWindow => "failureLiveNoWindow", Wording::Unkeyed,
    FailureLiveNoRetry => "failureLiveNoRetry", Wording::Unkeyed,
    FailureLiveFrame => "failureLiveFrame", Wording::Unkeyed,
    FailureSocketClosed => "failureSocketClosed", Wording::Unkeyed,
    FailureFileUnreadable => "failureFileUnreadable", Wording::Unkeyed,
    FailureFileUndecodable => "failureFileUndecodable", Wording::Unkeyed,
    FailurePlayerFrame => "failurePlayerFrame", Wording::Unkeyed,
    FailureBridgeAnswer => "failureBridgeAnswer", Wording::Unkeyed,
    FailureLiveTvSection => "failureLiveTvSection", Wording::Unkeyed,
    FailureLoginLeft => "failureLoginLeft", Wording::Unkeyed,
    FailureQuickConnectAbandoned => "failureQuickConnectAbandoned", Wording::Unkeyed,
    FailureSessionUnread => "failureSessionUnread", Wording::Unkeyed,
    FailureGroupUnresolved => "failureGroupUnresolved", Wording::Unkeyed,
    FailurePlaybackUnplanned => "failurePlaybackUnplanned", Wording::Unkeyed,
    FailureSetupUnfinished => "failureSetupUnfinished", Wording::Unkeyed,
    FailureMarkUnwritten => "failureMarkUnwritten", Wording::Unkeyed,
    FailurePreferencesUnmigrated => "failurePreferencesUnmigrated", Wording::Unkeyed,
    FailureLiveReport => "failureLiveReport", Wording::Unkeyed,
    FailurePluginPageRelease => "failurePluginPageRelease", Wording::Unkeyed,
    FailureMediaSession => "failureMediaSession", Wording::Unkeyed,
    BootSessionStalled => "bootSessionStalled", Wording::Unkeyed,
    BootRecheck => "bootRecheck", Wording::Unkeyed,
    FailureActivityUnread => "failureActivityUnread", Wording::Unkeyed,
    FailureAiringsUnread => "failureAiringsUnread", Wording::Unkeyed,
    FailureBrowseUnread => "failureBrowseUnread", Wording::Unkeyed,
    FailureCollectionsUnread => "failureCollectionsUnread", Wording::Unkeyed,
    FailureConfigurationUnread => "failureConfigurationUnread", Wording::Unkeyed,
    FailureDirectoryUnread => "failureDirectoryUnread", Wording::Unkeyed,
    FailureDashboardUnread => "failureDashboardUnread", Wording::Unkeyed,
    FailureFilingUnread => "failureFilingUnread", Wording::Unkeyed,
    FailureGroupItemsUnread => "failureGroupItemsUnread", Wording::Unkeyed,
    FailureGuideUnread => "failureGuideUnread", Wording::Unkeyed,
    FailureHomeUnread => "failureHomeUnread", Wording::Unkeyed,
    FailureMatchesUnread => "failureMatchesUnread", Wording::Unkeyed,
    FailureLibraryUnread => "failureLibraryUnread", Wording::Unkeyed,
    FailureLiveTvUnread => "failureLiveTvUnread", Wording::Unkeyed,
    FailureSignOut => "failureSignOut", Wording::Unkeyed,
    FailureMetadataUnread => "failureMetadataUnread", Wording::Unkeyed,
    FailurePreferencesUnread => "failurePreferencesUnread", Wording::Unkeyed,
    FailurePlaylistUnread => "failurePlaylistUnread", Wording::Unkeyed,
    FailurePlaylistsUnread => "failurePlaylistsUnread", Wording::Unkeyed,
    FailurePlaybackReport => "failurePlaybackReport", Wording::Unkeyed,
    FailurePlaybackUnread => "failurePlaybackUnread", Wording::Unkeyed,
    FailureSearchUnread => "failureSearchUnread", Wording::Unkeyed,
    FailureSeriesTimerUnread => "failureSeriesTimerUnread", Wording::Unkeyed,
    FailureSettingsUnread => "failureSettingsUnread", Wording::Unkeyed,
    FailureSetupStep => "failureSetupStep", Wording::Unkeyed,
    FailureQuickConnectUnread => "failureQuickConnectUnread", Wording::Unkeyed,
    FailureServersUnread => "failureServersUnread", Wording::Unkeyed,
    FailureResetPinUnread => "failureResetPinUnread", Wording::Unkeyed,
    FailureServerRemove => "failureServerRemove", Wording::Unkeyed,
    FailureSignInAgain => "failureSignInAgain", Wording::Unkeyed,
    FailureItemUnread => "failureItemUnread", Wording::Unkeyed,
    FailureSimilarUnread => "failureSimilarUnread", Wording::Unkeyed,
    FailureLatestUnread => "failureLatestUnread", Wording::Unkeyed,
    FailureSuggestionsUnread => "failureSuggestionsUnread", Wording::Unkeyed,
    FailureRecommendationsUnread => "failureRecommendationsUnread", Wording::Unkeyed,
    FailurePeopleUnread => "failurePeopleUnread", Wording::Unkeyed,
    FailureStudiosUnread => "failureStudiosUnread", Wording::Unkeyed,
    FailureGenresUnread => "failureGenresUnread", Wording::Unkeyed,
    FailureFiltersUnread => "failureFiltersUnread", Wording::Unkeyed,
    FailureImageUnread => "failureImageUnread", Wording::Unkeyed,
    FailureUserImageUnread => "failureUserImageUnread", Wording::Unkeyed,
    FailureTrickplayUnread => "failureTrickplayUnread", Wording::Unkeyed,
    FailureUsersUnread => "failureUsersUnread", Wording::Unkeyed,
    FailureProvidersUnread => "failureProvidersUnread", Wording::Unkeyed,
    FailureMappingUnread => "failureMappingUnread", Wording::Unkeyed,
    FailureTunerTypesUnread => "failureTunerTypesUnread", Wording::Unkeyed,
    FailureTunersUnread => "failureTunersUnread", Wording::Unkeyed,
    FailureTunerDiscovery => "failureTunerDiscovery", Wording::Unkeyed,
    FailureLineupsUnread => "failureLineupsUnread", Wording::Unkeyed,
    FailurePlaylistSharingUnread => "failurePlaylistSharingUnread", Wording::Unkeyed,
    FailureItemImagesUnread => "failureItemImagesUnread", Wording::Unkeyed,
    FailureImageProvidersUnread => "failureImageProvidersUnread", Wording::Unkeyed,
    FailureContentTypesUnread => "failureContentTypesUnread", Wording::Unkeyed,
    FailurePluginPageUnread => "failurePluginPageUnread", Wording::Unkeyed,
    FailureDismiss => "failureDismiss", Wording::Unkeyed,
    FailuresTitle => "failuresTitle", Wording::Unkeyed,
    FailuresEmpty => "failuresEmpty", Wording::Unkeyed,
    FailureSavedSignInRejected => "failureSavedSignInRejected", Wording::Unkeyed,
    FailureRemoveUnrevoked => "failureRemoveUnrevoked", Wording::Unkeyed,
    FailureQuickConnectSignInExpired => "failureQuickConnectSignInExpired", Wording::Unkeyed,
    FailureQuickConnectSignInDisabled => "failureQuickConnectSignInDisabled", Wording::Unkeyed,
    FailureResetPinRefused => "failureResetPinRefused", Wording::Unkeyed,
    FailureLoginMoved => "failureLoginMoved", Wording::Unkeyed,
    FailureStageLoginOnly => "failureStageLoginOnly", Wording::Unkeyed,
    HomeMyMedia => "homeMyMedia", Wording::Reference(Sentence::HeaderMyMedia),
    HomeTabHome => "homeTabHome", Wording::Reference(Sentence::Home),
    HomeTabFavorites => "homeTabFavorites", Wording::Reference(Sentence::Favorites),
    FavoritesMovies => "favoritesMovies", Wording::Unkeyed,
    FavoritesShows => "favoritesShows", Wording::Unkeyed,
    FavoritesSeasons => "favoritesSeasons", Wording::Unkeyed,
    FavoritesEpisodes => "favoritesEpisodes", Wording::Unkeyed,
    FavoritesVideos => "favoritesVideos", Wording::Unkeyed,
    FavoritesMusicVideos => "favoritesMusicVideos", Wording::Unkeyed,
    FavoritesCollections => "favoritesCollections", Wording::Unkeyed,
    FavoritesPlaylists => "favoritesPlaylists", Wording::Unkeyed,
    FavoritesPeople => "favoritesPeople", Wording::Unkeyed,
    FavoritesArtists => "favoritesArtists", Wording::Unkeyed,
    FavoritesAlbums => "favoritesAlbums", Wording::Unkeyed,
    FavoritesSongs => "favoritesSongs", Wording::Unkeyed,
    FavoritesBooks => "favoritesBooks", Wording::Unkeyed,
    FavoritesChannels => "favoritesChannels", Wording::Unkeyed,
    FavoritesPhotoAlbums => "favoritesPhotoAlbums", Wording::Unkeyed,
    FavoritesPhotos => "favoritesPhotos", Wording::Unkeyed,
    FailureFavoritesUnread => "failureFavoritesUnread", Wording::Unkeyed,
    HomeLiveTv => "homeLiveTv", Wording::Reference(Sentence::LiveTV),
    HomeContinueWatching => "homeContinueWatching", Wording::Reference(Sentence::HeaderContinueWatching),
    HomeContinueListening => "homeContinueListening", Wording::Reference(Sentence::HeaderContinueListening),
    HomeContinueReading => "homeContinueReading", Wording::Reference(Sentence::HeaderContinueReading),
    HomeLatest => "homeLatest", Wording::Reference(Sentence::LatestFromLibrary),
    HomeNextUp => "homeNextUp", Wording::Reference(Sentence::NextUp),
    HomeEmptyHeading => "homeEmptyHeading", Wording::Reference(Sentence::MessageNothingHere),
    HomeEmptyAdministrator => "homeEmptyAdministrator", Wording::Reference(Sentence::NoCreatedLibraries),
    HomeEmptyUser => "homeEmptyUser", Wording::Reference(Sentence::AskAdminToCreateLibrary),
    LibrarySort => "librarySort", Wording::Unkeyed,
    SortName => "sortName", Wording::Unkeyed,
    SortNameDescending => "sortNameDescending", Wording::Unkeyed,
    SortDateAdded => "sortDateAdded", Wording::Unkeyed,
    SortReleaseDate => "sortReleaseDate", Wording::Unkeyed,
    SortCommunityRating => "sortCommunityRating", Wording::Unkeyed,
    SortRandom => "sortRandom", Wording::Unkeyed,
    GridPaging => "gridPaging", Wording::Unkeyed,
    FilterIndicator => "filterIndicator", Wording::Unkeyed,
    FilterClose => "filterClose", Wording::Unkeyed,
    FilterClear => "filterClear", Wording::Unkeyed,
    FilterPlayed => "filterPlayed", Wording::Unkeyed,
    FilterResumable => "filterResumable", Wording::Unkeyed,
    FilterFavorite => "filterFavorite", Wording::Unkeyed,
    FilterHasSubtitles => "filterHasSubtitles", Wording::Unkeyed,
    FilterHd => "filterHd", Wording::Unkeyed,
    FilterUhd => "filterUhd", Wording::Unkeyed,
    LibraryTabItems => "libraryTabItems", Wording::Unkeyed,
    LibraryTabSuggestions => "libraryTabSuggestions", Wording::Unkeyed,
    LibraryTabFavorites => "libraryTabFavorites", Wording::Unkeyed,
    LibraryTabUpcoming => "libraryTabUpcoming", Wording::Unkeyed,
    LibraryTabEpisodes => "libraryTabEpisodes", Wording::Unkeyed,
    LibraryTabSongs => "libraryTabSongs", Wording::Unkeyed,
    LibraryTabAlbumArtists => "libraryTabAlbumArtists", Wording::Unkeyed,
    LibraryTabArtists => "libraryTabArtists", Wording::Unkeyed,
    LibraryTabGenres => "libraryTabGenres", Wording::Unkeyed,
    LibraryTabStudios => "libraryTabStudios", Wording::Unkeyed,
    LibraryTabNetworks => "libraryTabNetworks", Wording::Unkeyed,
    SearchPlaceholder => "searchPlaceholder", Wording::Unkeyed,
    SearchSuggestions => "searchSuggestions", Wording::Unkeyed,
    SearchResultsEmpty => "searchResultsEmpty", Wording::Unkeyed,
    SearchMovies => "searchMovies", Wording::Unkeyed,
    SearchShows => "searchShows", Wording::Unkeyed,
    SearchEpisodes => "searchEpisodes", Wording::Unkeyed,
    SearchPlaylists => "searchPlaylists", Wording::Unkeyed,
    SearchArtists => "searchArtists", Wording::Unkeyed,
    SearchAlbums => "searchAlbums", Wording::Unkeyed,
    SearchSongs => "searchSongs", Wording::Unkeyed,
    SearchVideos => "searchVideos", Wording::Unkeyed,
    SearchChannels => "searchChannels", Wording::Unkeyed,
    SearchPhotoAlbums => "searchPhotoAlbums", Wording::Unkeyed,
    SearchPhotos => "searchPhotos", Wording::Unkeyed,
    SearchAudioBooks => "searchAudioBooks", Wording::Unkeyed,
    SearchBooks => "searchBooks", Wording::Unkeyed,
    SearchCollections => "searchCollections", Wording::Unkeyed,
    DetailOverview => "detailOverview", Wording::Unkeyed,
    DetailSimilar => "detailSimilar", Wording::Unkeyed,
    DetailSeasons => "detailSeasons", Wording::Unkeyed,
    DetailEpisodes => "detailEpisodes", Wording::Unkeyed,
    DetailTracks => "detailTracks", Wording::Unkeyed,
    DetailAlbums => "detailAlbums", Wording::Unkeyed,
    DetailItems => "detailItems", Wording::Unkeyed,
    DetailMarkPlayed => "detailMarkPlayed", Wording::Unkeyed,
    DetailMarkUnplayed => "detailMarkUnplayed", Wording::Unkeyed,
    DetailFavorite => "detailFavorite", Wording::Unkeyed,
    DetailUnfavorite => "detailUnfavorite", Wording::Unkeyed,
    DetailMoreCommands => "detailMoreCommands", Wording::Unkeyed,
    NavBack => "navBack", Wording::Reference(Sentence::ButtonBack),
    NavPrevious => "navPrevious", Wording::Reference(Sentence::Previous),
    NavNext => "navNext", Wording::Reference(Sentence::Next),
    NavDrawer => "navDrawer", Wording::Reference(Sentence::Menu),
    NavMedia => "navMedia", Wording::Reference(Sentence::HeaderMedia),
    NavAdministration => "navAdministration", Wording::Reference(Sentence::HeaderAdmin),
    NavUser => "navUser", Wording::Reference(Sentence::HeaderUser),
    NavMetadata => "navMetadata", Wording::Reference(Sentence::MetadataManager),
    NavHome => "navHome", Wording::Reference(Sentence::Home),
    NavSearch => "navSearch", Wording::Unkeyed,
    NavLogout => "navLogout", Wording::Reference(Sentence::ButtonSignOut),
    StatusLoading => "statusLoading", Wording::Unkeyed,
    FailureServerUnreachable => "failureServerUnreachable", Wording::Unkeyed,
    FailureCredentialsRejected => "failureCredentialsRejected", Wording::Unkeyed,
    FailureTokenRejected => "failureTokenRejected", Wording::Unkeyed,
    FailureServerBelowMinimum => "failureServerBelowMinimum", Wording::Unkeyed,
    FailureRelay => "failureRelay", Wording::Unkeyed,
    FailureNotThisBrowser => "failureNotThisBrowser", Wording::Unkeyed,
    FailureForeignOrigin => "failureForeignOrigin", Wording::Unkeyed,
    FailureNoSession => "failureNoSession", Wording::Unkeyed,
    FailureNotRelayed => "failureNotRelayed", Wording::Unkeyed,
    WarningOffSnapshot => "warningOffSnapshot", Wording::Unkeyed,
    DetailPlay => "detailPlay", Wording::Unkeyed,
    DetailResume => "detailResume", Wording::Unkeyed,
    DetailPlayAll => "detailPlayAll", Wording::Unkeyed,
    DetailShuffle => "detailShuffle", Wording::Unkeyed,
    DetailInstantMix => "detailInstantMix", Wording::Unkeyed,
    PlayerPlay => "playerPlay", Wording::Unkeyed,
    PlayerPause => "playerPause", Wording::Unkeyed,
    PlayerSkipBack => "playerSkipBack", Wording::Unkeyed,
    PlayerSkipForward => "playerSkipForward", Wording::Unkeyed,
    PlayerPrevious => "playerPrevious", Wording::Unkeyed,
    PlayerNext => "playerNext", Wording::Unkeyed,
    PlayerMute => "playerMute", Wording::Unkeyed,
    PlayerUnmute => "playerUnmute", Wording::Unkeyed,
    PlayerFullscreen => "playerFullscreen", Wording::Unkeyed,
    PlayerExitFullscreen => "playerExitFullscreen", Wording::Unkeyed,
    PlayerAudio => "playerAudio", Wording::Unkeyed,
    PlayerSubtitles => "playerSubtitles", Wording::Unkeyed,
    PlayerSubtitlesOff => "playerSubtitlesOff", Wording::Unkeyed,
    PlayerQuality => "playerQuality", Wording::Unkeyed,
    PlayerQualityAuto => "playerQualityAuto", Wording::Unkeyed,
    PlayerQualityLimit => "playerQualityLimit", Wording::Unkeyed,
    PlayerChapters => "playerChapters", Wording::Unkeyed,
    PlayerVersion => "playerVersion", Wording::Unkeyed,
    PlayerRepeatMode => "playerRepeatMode", Wording::Unkeyed,
    PlayerQueue => "playerQueue", Wording::Unkeyed,
    PlayerFavorite => "playerFavorite", Wording::Unkeyed,
    PlayerUnfavorite => "playerUnfavorite", Wording::Unkeyed,
    PlayerLeave => "playerLeave", Wording::Unkeyed,
    PlayerEndsAt => "playerEndsAt", Wording::Unkeyed,
    PlayerFetching => "playerFetching", Wording::Unkeyed,
    PlayerSettings => "playerSettings", Wording::Unkeyed,
    PlayerEpisode => "playerEpisode", Wording::Unkeyed,
    PlayerNextItem => "playerNextItem", Wording::Unkeyed,
    PlayerDirect => "playerDirect", Wording::Unkeyed,
    PlayerTranscoding => "playerTranscoding", Wording::Unkeyed,
    PlayerTranscodingBurningInSubtitles => "playerTranscodingBurningInSubtitles", Wording::Unkeyed,
    QueueTitle => "queueTitle", Wording::Unkeyed,
    QueueEmpty => "queueEmpty", Wording::Unkeyed,
    QueueRemove => "queueRemove", Wording::Unkeyed,
    QueueShuffle => "queueShuffle", Wording::Unkeyed,
    QueueRepeatOff => "queueRepeatOff", Wording::Unkeyed,
    QueueRepeatOne => "queueRepeatOne", Wording::Unkeyed,
    QueueRepeatAll => "queueRepeatAll", Wording::Unkeyed,
    QueueBack => "queueBack", Wording::Unkeyed,
    FailureNoMediaSource => "failureNoMediaSource", Wording::Unkeyed,
    FailureNoPlayableSource => "failureNoPlayableSource", Wording::Unkeyed,
    FailureTranscodeRefused => "failureTranscodeRefused", Wording::Unkeyed,
    FailurePlaybackSuperseded => "failurePlaybackSuperseded", Wording::Unkeyed,
    FailureNotRelayable => "failureNotRelayable", Wording::Unkeyed,
    FailurePlaybackLapsed => "failurePlaybackLapsed", Wording::Unkeyed,
    FailureDecode => "failureDecode", Wording::Unkeyed,
    FailureStreamDropped => "failureStreamDropped", Wording::Unkeyed,
    FailurePlaybackServer => "failurePlaybackServer", Wording::Unkeyed,
    FailurePlaybackHlsFatal => "failurePlaybackHlsFatal", Wording::Unkeyed,
    FailureManifestNotRewritable => "failureManifestNotRewritable", Wording::Unkeyed,
    FailureManifestTooLarge => "failureManifestTooLarge", Wording::Unkeyed,
    FailureForeignNotObserved => "failureForeignNotObserved", Wording::Unkeyed,
    FailureItemRemoved => "failureItemRemoved", Wording::Unkeyed,
    NavCollections => "navCollections", Wording::Unkeyed,
    NavPlaylists => "navPlaylists", Wording::Unkeyed,
    CollectionCreate => "collectionCreate", Wording::Unkeyed,
    PlaylistCreate => "playlistCreate", Wording::Unkeyed,
    PlaylistRename => "playlistRename", Wording::Unkeyed,
    PlaylistDelete => "playlistDelete", Wording::Unkeyed,
    PlaylistRemove => "playlistRemove", Wording::Unkeyed,
    PlaylistMoveUp => "playlistMoveUp", Wording::Unkeyed,
    PlaylistMoveDown => "playlistMoveDown", Wording::Unkeyed,
    PlaylistOpenAccess => "playlistOpenAccess", Wording::Unkeyed,
    PlaylistUnshare => "playlistUnshare", Wording::Unkeyed,
    FailureWroteItemSave => "failureWroteItemSave", Wording::Unkeyed,
    FailureWroteItemDelete => "failureWroteItemDelete", Wording::Unkeyed,
    FailureWroteItemContentType => "failureWroteItemContentType", Wording::Unkeyed,
    FailureWroteItemIdentify => "failureWroteItemIdentify", Wording::Unkeyed,
    FailureWroteItemImageUpload => "failureWroteItemImageUpload", Wording::Unkeyed,
    FailureWroteItemImageRemove => "failureWroteItemImageRemove", Wording::Unkeyed,
    FailureWroteItemImageMove => "failureWroteItemImageMove", Wording::Unkeyed,
    FailureWroteItemImageDownload => "failureWroteItemImageDownload", Wording::Unkeyed,
    MetadataPartFields => "metadataPartFields", Wording::Unkeyed,
    MetadataPartIdentify => "metadataPartIdentify", Wording::Unkeyed,
    MetadataPartImages => "metadataPartImages", Wording::Unkeyed,
    MetadataPartLocks => "metadataPartLocks", Wording::Unkeyed,
    MetadataPartContentType => "metadataPartContentType", Wording::Unkeyed,
    MetadataPartDeletion => "metadataPartDeletion", Wording::Unkeyed,
    MetadataSave => "metadataSave", Wording::Unkeyed,
    MetadataClose => "metadataClose", Wording::Unkeyed,
    MetadataDelete => "metadataDelete", Wording::Unkeyed,
    MetadataDeleteWarning => "metadataDeleteWarning", Wording::Unkeyed,
    MetadataLocked => "metadataLocked", Wording::Unkeyed,
    MetadataUnlocked => "metadataUnlocked", Wording::Unkeyed,
    MetadataPeople => "metadataPeople", Wording::Unkeyed,
    MetadataPersonAdd => "metadataPersonAdd", Wording::Unkeyed,
    MetadataPersonRemove => "metadataPersonRemove", Wording::Unkeyed,
    MetadataProviders => "metadataProviders", Wording::Unkeyed,
    MetadataIdentifyName => "metadataIdentifyName", Wording::Unkeyed,
    MetadataIdentifyYear => "metadataIdentifyYear", Wording::Unkeyed,
    MetadataIdentifyProvider => "metadataIdentifyProvider", Wording::Unkeyed,
    MetadataIdentifyProviderId => "metadataIdentifyProviderId", Wording::Unkeyed,
    MetadataIdentifyRun => "metadataIdentifyRun", Wording::Unkeyed,
    MetadataChoose => "metadataChoose", Wording::Unkeyed,
    MetadataApply => "metadataApply", Wording::Unkeyed,
    MetadataApplyAsk => "metadataApplyAsk", Wording::Unkeyed,
    MetadataCancel => "metadataCancel", Wording::Unkeyed,
    MetadataReplaceImages => "metadataReplaceImages", Wording::Unkeyed,
    MetadataOpen => "metadataOpen", Wording::Unkeyed,
    ArtworkPrimary => "artworkPrimary", Wording::Unkeyed,
    ArtworkBackdrop => "artworkBackdrop", Wording::Unkeyed,
    ArtworkThumb => "artworkThumb", Wording::Unkeyed,
    ArtworkLogo => "artworkLogo", Wording::Unkeyed,
    ArtworkBanner => "artworkBanner", Wording::Unkeyed,
    ArtworkArt => "artworkArt", Wording::Unkeyed,
    ArtworkRemove => "artworkRemove", Wording::Unkeyed,
    ArtworkMoveEarlier => "artworkMoveEarlier", Wording::Unkeyed,
    ArtworkMoveLater => "artworkMoveLater", Wording::Unkeyed,
    ArtworkUpload => "artworkUpload", Wording::Unkeyed,
    ArtworkSearch => "artworkSearch", Wording::Unkeyed,
    ArtworkDownload => "artworkDownload", Wording::Unkeyed,
    ConfirmDeleteItem => "confirmDeleteItem", Wording::Unkeyed,
    SearchPeople => "searchPeople", Wording::Unkeyed,
    SearchStudios => "searchStudios", Wording::Unkeyed,
    SearchPrograms => "searchPrograms", Wording::Unkeyed,
    NavRemote => "navRemote", Wording::Unkeyed,
    LiveUnavailable => "liveUnavailable", Wording::Unkeyed,
    PlayerRemote => "playerRemote", Wording::Unkeyed,
    PlayerStop => "playerStop", Wording::Unkeyed,
    RemoteTitle => "remoteTitle", Wording::Unkeyed,
    RemoteEmpty => "remoteEmpty", Wording::Unkeyed,
    RemoteLeave => "remoteLeave", Wording::Unkeyed,
    RemoteNothingPlaying => "remoteNothingPlaying", Wording::Unkeyed,
    RemoteHeading => "remoteHeading", Wording::Unkeyed,
    FailureServerRestarting => "failureServerRestarting", Wording::Unkeyed,
    FailureServerShuttingDown => "failureServerShuttingDown", Wording::Unkeyed,
    FailureUserDeleted => "failureUserDeleted", Wording::Unkeyed,
    FailureRemoteTaken => "failureRemoteTaken", Wording::Unkeyed,
    FailureRemoteTargetGone => "failureRemoteTargetGone", Wording::Unkeyed,
    FailureRemoteControlled => "failureRemoteControlled", Wording::Unkeyed,
    FailureUnknownTarget => "failureUnknownTarget", Wording::Unkeyed,
    FailureNotDriving => "failureNotDriving", Wording::Unkeyed,
    FailureTargetRefused => "failureTargetRefused", Wording::Unkeyed,
    NavSyncPlay => "navSyncPlay", Wording::Reference(Sentence::ButtonSyncPlay),
    PlayerSyncPlay => "playerSyncPlay", Wording::Unkeyed,
    SyncPlayTitle => "syncPlayTitle", Wording::Unkeyed,
    SyncPlayEmpty => "syncPlayEmpty", Wording::Unkeyed,
    SyncPlayActive => "syncPlayActive", Wording::Unkeyed,
    SyncPlayWaiting => "syncPlayWaiting", Wording::Unkeyed,
    SyncPlayParticipants => "syncPlayParticipants", Wording::Unkeyed,
    SyncPlayStateIdle => "syncPlayStateIdle", Wording::Unkeyed,
    SyncPlayStateWaiting => "syncPlayStateWaiting", Wording::Unkeyed,
    SyncPlayStatePaused => "syncPlayStatePaused", Wording::Unkeyed,
    SyncPlayStatePlaying => "syncPlayStatePlaying", Wording::Unkeyed,
    SyncPlayNamedForItem => "syncPlayNamedForItem", Wording::Unkeyed,
    SyncPlayNamedForUser => "syncPlayNamedForUser", Wording::Unkeyed,
    SyncPlayLinkDown => "syncPlayLinkDown", Wording::Unkeyed,
    FailureGroupLeft => "failureGroupLeft", Wording::Unkeyed,
    FailureGroupRemoved => "failureGroupRemoved", Wording::Unkeyed,
    FailureGroupRemote => "failureGroupRemote", Wording::Unkeyed,
    FailureGroupNotInGroup => "failureGroupNotInGroup", Wording::Unkeyed,
    FailureGroupNoSuchGroup => "failureGroupNoSuchGroup", Wording::Unkeyed,
    FailureGroupLibraryDenied => "failureGroupLibraryDenied", Wording::Unkeyed,
    FailureGroupUnplayable => "failureGroupUnplayable", Wording::Unkeyed,
    FailureNotGrouped => "failureNotGrouped", Wording::Unkeyed,
    FailureGroupRefused => "failureGroupRefused", Wording::Unkeyed,
    FailureRemoteGrouped => "failureRemoteGrouped", Wording::Unkeyed,
    FailureDisplacedByPlayback => "failureDisplacedByPlayback", Wording::Unkeyed,
    FailureDisplacedByGroup => "failureDisplacedByGroup", Wording::Unkeyed,
    HomeOnNow => "homeOnNow", Wording::Reference(Sentence::HeaderOnNow),
    LiveTvTitle => "liveTvTitle", Wording::Unkeyed,
    LiveTvTabPrograms => "liveTvTabPrograms", Wording::Reference(Sentence::Programs),
    ProgramsShows => "programsShows", Wording::Unkeyed,
    ProgramsMovies => "programsMovies", Wording::Unkeyed,
    ProgramsSports => "programsSports", Wording::Unkeyed,
    ProgramsKids => "programsKids", Wording::Unkeyed,
    ProgramsNews => "programsNews", Wording::Unkeyed,
    FailureProgramsUnread => "failureProgramsUnread", Wording::Unkeyed,
    LiveTvTabGuide => "liveTvTabGuide", Wording::Unkeyed,
    LiveTvTabChannels => "liveTvTabChannels", Wording::Unkeyed,
    LiveTvTabRecordings => "liveTvTabRecordings", Wording::Unkeyed,
    LiveTvTabSchedule => "liveTvTabSchedule", Wording::Unkeyed,
    LiveTvTabSeries => "liveTvTabSeries", Wording::Unkeyed,
    GuideNow => "guideNow", Wording::Unkeyed,
    GuideEarlier => "guideEarlier", Wording::Unkeyed,
    GuideLater => "guideLater", Wording::Unkeyed,
    GuideEmpty => "guideEmpty", Wording::Unkeyed,
    GuideBadgeLive => "guideBadgeLive", Wording::Unkeyed,
    GuideBadgeNew => "guideBadgeNew", Wording::Unkeyed,
    GuideBadgePremiere => "guideBadgePremiere", Wording::Unkeyed,
    GuideBadgeRepeat => "guideBadgeRepeat", Wording::Unkeyed,
    ChannelsTv => "channelsTv", Wording::Unkeyed,
    ChannelsRadio => "channelsRadio", Wording::Unkeyed,
    ChannelsEmpty => "channelsEmpty", Wording::Unkeyed,
    ChannelFavorite => "channelFavorite", Wording::Unkeyed,
    ChannelUnfavorite => "channelUnfavorite", Wording::Unkeyed,
    ProgramChannel => "programChannel", Wording::Unkeyed,
    ProgramAirtime => "programAirtime", Wording::Unkeyed,
    ProgramRecord => "programRecord", Wording::Unkeyed,
    ProgramRecordSeries => "programRecordSeries", Wording::Unkeyed,
    ProgramCancelRecording => "programCancelRecording", Wording::Unkeyed,
    ProgramCancelSeries => "programCancelSeries", Wording::Unkeyed,
    RecordingsEmpty => "recordingsEmpty", Wording::Unkeyed,
    RecordingsLatest => "recordingsLatest", Wording::Unkeyed,
    ScheduleActive => "scheduleActive", Wording::Unkeyed,
    ScheduleEmpty => "scheduleEmpty", Wording::Unkeyed,
    SeriesTimerAnytime => "seriesTimerAnytime", Wording::Unkeyed,
    SeriesTimerAllChannels => "seriesTimerAllChannels", Wording::Unkeyed,
    SeriesTimerOneChannel => "seriesTimerOneChannel", Wording::Unkeyed,
    SeriesEmpty => "seriesEmpty", Wording::Unkeyed,
    SeriesEdit => "seriesEdit", Wording::Unkeyed,
    SeriesSave => "seriesSave", Wording::Unkeyed,
    SeriesClose => "seriesClose", Wording::Unkeyed,
    SeriesDayPattern => "seriesDayPattern", Wording::Unkeyed,
    SeriesDayPatternAny => "seriesDayPatternAny", Wording::Unkeyed,
    SeriesDays => "seriesDays", Wording::Unkeyed,
    SeriesAnyChannel => "seriesAnyChannel", Wording::Unkeyed,
    SeriesAnyTime => "seriesAnyTime", Wording::Unkeyed,
    SeriesNewOnly => "seriesNewOnly", Wording::Unkeyed,
    SeriesSkipInLibrary => "seriesSkipInLibrary", Wording::Unkeyed,
    SeriesKeepUntil => "seriesKeepUntil", Wording::Unkeyed,
    SeriesKeepUpTo => "seriesKeepUpTo", Wording::Unkeyed,
    SeriesPriority => "seriesPriority", Wording::Unkeyed,
    SeriesPrePadding => "seriesPrePadding", Wording::Unkeyed,
    SeriesPostPadding => "seriesPostPadding", Wording::Unkeyed,
    TimerOptions => "timerOptions", Wording::Unkeyed,
    TimerStartEarly => "timerStartEarly", Wording::Unkeyed,
    TimerStopLate => "timerStopLate", Wording::Unkeyed,
    TimerMinutesBefore => "timerMinutesBefore", Wording::Unkeyed,
    TimerMinutesAfter => "timerMinutesAfter", Wording::Unkeyed,
    TimerSave => "timerSave", Wording::Unkeyed,
    TimerCancelRecording => "timerCancelRecording", Wording::Unkeyed,
    TimerClose => "timerClose", Wording::Unkeyed,
    PlayerLive => "playerLive", Wording::Unkeyed,
    PlayerTuning => "playerTuning", Wording::Unkeyed,
    PlayerLiveEdge => "playerLiveEdge", Wording::Unkeyed,
    PlayerRecord => "playerRecord", Wording::Unkeyed,
    PlayerRecording => "playerRecording", Wording::Unkeyed,
    PlayerChannel => "playerChannel", Wording::Unkeyed,
    PlayerChannelPrevious => "playerChannelPrevious", Wording::Unkeyed,
    PlayerChannelNext => "playerChannelNext", Wording::Unkeyed,
    FailureLiveTvNoService => "failureLiveTvNoService", Wording::Unkeyed,
    FailureLiveTvDenied => "failureLiveTvDenied", Wording::Unkeyed,
    FailureNoTuner => "failureNoTuner", Wording::Unkeyed,
    FailureTunerGone => "failureTunerGone", Wording::Unkeyed,
    FailureLiveStreamDropped => "failureLiveStreamDropped", Wording::Unkeyed,
    FailureTunerReleased => "failureTunerReleased", Wording::Unkeyed,
    FailureGuideOutOfRange => "failureGuideOutOfRange", Wording::Unkeyed,
    FailureLiveNotRelayable => "failureLiveNotRelayable", Wording::Unkeyed,
    NavDashboard => "navDashboard", Wording::Reference(Sentence::TabDashboard),
    PluginsTitle => "pluginsTitle", Wording::Unkeyed,
    PluginsEnable => "pluginsEnable", Wording::Unkeyed,
    PluginsDisable => "pluginsDisable", Wording::Unkeyed,
    PluginsUninstall => "pluginsUninstall", Wording::Unkeyed,
    PluginsConfigurationPages => "pluginsConfigurationPages", Wording::Unkeyed,
    ConfirmUninstallPlugin => "confirmUninstallPlugin", Wording::Unkeyed,
    ConfirmTypeName => "confirmTypeName", Wording::Unkeyed,
    ConfirmProceed => "confirmProceed", Wording::Unkeyed,
    ConfirmCancel => "confirmCancel", Wording::Unkeyed,
    FailureWrotePluginEnable => "failureWrotePluginEnable", Wording::Unkeyed,
    FailureWrotePluginDisable => "failureWrotePluginDisable", Wording::Unkeyed,
    FailureWrotePluginUninstall => "failureWrotePluginUninstall", Wording::Unkeyed,
    FailureWrotePluginConfiguration => "failureWrotePluginConfiguration", Wording::Unkeyed,
    DashboardHome => "dashboardHome", Wording::Unkeyed,
    DashboardServer => "dashboardServer", Wording::Unkeyed,
    DashboardVersion => "dashboardVersion", Wording::Unkeyed,
    DashboardSessions => "dashboardSessions", Wording::Unkeyed,
    DashboardSessionNothing => "dashboardSessionNothing", Wording::Unkeyed,
    DashboardRunningTasks => "dashboardRunningTasks", Wording::Unkeyed,
    DashboardScanning => "dashboardScanning", Wording::Unkeyed,
    DashboardScanAll => "dashboardScanAll", Wording::Unkeyed,
    DashboardRestart => "dashboardRestart", Wording::Unkeyed,
    DashboardShutdown => "dashboardShutdown", Wording::Unkeyed,
    DashboardRestartRequired => "dashboardRestartRequired", Wording::Unkeyed,
    DashboardSettings => "dashboardSettings", Wording::Unkeyed,
    DashboardNetworking => "dashboardNetworking", Wording::Unkeyed,
    DashboardBranding => "dashboardBranding", Wording::Unkeyed,
    DashboardResume => "dashboardResume", Wording::Unkeyed,
    DashboardStreaming => "dashboardStreaming", Wording::Unkeyed,
    DashboardTranscoding => "dashboardTranscoding", Wording::Unkeyed,
    DashboardTrickplay => "dashboardTrickplay", Wording::Unkeyed,
    DashboardPaths => "dashboardPaths", Wording::Unkeyed,
    DashboardQuickConnect => "dashboardQuickConnect", Wording::Unkeyed,
    DashboardPerformance => "dashboardPerformance", Wording::Unkeyed,
    NetworkingAddresses => "networkingAddresses", Wording::Unkeyed,
    NetworkingRemote => "networkingRemote", Wording::Unkeyed,
    NetworkingProtocols => "networkingProtocols", Wording::Unkeyed,
    NetworkingDiscovery => "networkingDiscovery", Wording::Unkeyed,
    TranscodingHardwareEncoding => "transcodingHardwareEncoding", Wording::Unkeyed,
    TranscodingEncodingFormat => "transcodingEncodingFormat", Wording::Unkeyed,
    GeneralServerName => "generalServerName", Wording::Unkeyed,
    GeneralServerNameHelp => "generalServerNameHelp", Wording::Unkeyed,
    GeneralDisplayLanguage => "generalDisplayLanguage", Wording::Unkeyed,
    GeneralDisplayLanguageHelp => "generalDisplayLanguageHelp", Wording::Unkeyed,
    GeneralMetadataPath => "generalMetadataPath", Wording::Unkeyed,
    GeneralMetadataPathHelp => "generalMetadataPathHelp", Wording::Unkeyed,
    GeneralQuickConnect => "generalQuickConnect", Wording::Unkeyed,
    GeneralScanConcurrency => "generalScanConcurrency", Wording::Unkeyed,
    GeneralScanConcurrencyHelp => "generalScanConcurrencyHelp", Wording::Unkeyed,
    NetworkingPort => "networkingPort", Wording::Unkeyed,
    NetworkingPortHelp => "networkingPortHelp", Wording::Unkeyed,
    NetworkingBaseUrl => "networkingBaseUrl", Wording::Unkeyed,
    NetworkingBaseUrlHelp => "networkingBaseUrlHelp", Wording::Unkeyed,
    NetworkingLanNetworks => "networkingLanNetworks", Wording::Unkeyed,
    NetworkingLanNetworksHelp => "networkingLanNetworksHelp", Wording::Unkeyed,
    NetworkingKnownProxies => "networkingKnownProxies", Wording::Unkeyed,
    NetworkingKnownProxiesHelp => "networkingKnownProxiesHelp", Wording::Unkeyed,
    NetworkingRemoteAccess => "networkingRemoteAccess", Wording::Unkeyed,
    NetworkingRemoteAccessHelp => "networkingRemoteAccessHelp", Wording::Unkeyed,
    NetworkingRemoteFilter => "networkingRemoteFilter", Wording::Unkeyed,
    NetworkingRemoteFilterHelp => "networkingRemoteFilterHelp", Wording::Unkeyed,
    NetworkingPublicPort => "networkingPublicPort", Wording::Unkeyed,
    NetworkingPublicPortHelp => "networkingPublicPortHelp", Wording::Unkeyed,
    NetworkingIpv4 => "networkingIpv4", Wording::Unkeyed,
    NetworkingIpv4Help => "networkingIpv4Help", Wording::Unkeyed,
    NetworkingIpv6 => "networkingIpv6", Wording::Unkeyed,
    NetworkingIpv6Help => "networkingIpv6Help", Wording::Unkeyed,
    NetworkingAutoDiscovery => "networkingAutoDiscovery", Wording::Unkeyed,
    NetworkingAutoDiscoveryHelp => "networkingAutoDiscoveryHelp", Wording::Unkeyed,
    BrandingSplashscreen => "brandingSplashscreen", Wording::Unkeyed,
    BrandingLoginDisclaimer => "brandingLoginDisclaimer", Wording::Unkeyed,
    BrandingLoginDisclaimerHelp => "brandingLoginDisclaimerHelp", Wording::Unkeyed,
    BrandingCustomCss => "brandingCustomCss", Wording::Unkeyed,
    BrandingCustomCssHelp => "brandingCustomCssHelp", Wording::Unkeyed,
    ResumeMinimumPercentage => "resumeMinimumPercentage", Wording::Unkeyed,
    ResumeMinimumPercentageHelp => "resumeMinimumPercentageHelp", Wording::Unkeyed,
    ResumeMaximumPercentage => "resumeMaximumPercentage", Wording::Unkeyed,
    ResumeMaximumPercentageHelp => "resumeMaximumPercentageHelp", Wording::Unkeyed,
    ResumeMinimumAudiobook => "resumeMinimumAudiobook", Wording::Unkeyed,
    ResumeMinimumAudiobookHelp => "resumeMinimumAudiobookHelp", Wording::Unkeyed,
    ResumeMaximumAudiobook => "resumeMaximumAudiobook", Wording::Unkeyed,
    ResumeMaximumAudiobookHelp => "resumeMaximumAudiobookHelp", Wording::Unkeyed,
    ResumeMinimumDuration => "resumeMinimumDuration", Wording::Unkeyed,
    ResumeMinimumDurationHelp => "resumeMinimumDurationHelp", Wording::Unkeyed,
    StreamingBitrateLimit => "streamingBitrateLimit", Wording::Unkeyed,
    StreamingBitrateLimitHelp => "streamingBitrateLimitHelp", Wording::Unkeyed,
    TranscodingHardwareAcceleration => "transcodingHardwareAcceleration", Wording::Unkeyed,
    TranscodingHardwareAccelerationHelp => "transcodingHardwareAccelerationHelp", Wording::Unkeyed,
    TranscodingAccelerationNone => "transcodingAccelerationNone", Wording::Unkeyed,
    TranscodingAccelerationAmf => "transcodingAccelerationAmf", Wording::Unkeyed,
    TranscodingAccelerationNvenc => "transcodingAccelerationNvenc", Wording::Unkeyed,
    TranscodingAccelerationQsv => "transcodingAccelerationQsv", Wording::Unkeyed,
    TranscodingAccelerationVaapi => "transcodingAccelerationVaapi", Wording::Unkeyed,
    TranscodingAccelerationRkmpp => "transcodingAccelerationRkmpp", Wording::Unkeyed,
    TranscodingAccelerationVideoToolbox => "transcodingAccelerationVideoToolbox", Wording::Unkeyed,
    TranscodingAccelerationV4l2m2m => "transcodingAccelerationV4l2m2m", Wording::Unkeyed,
    TranscodingEnableHardwareEncoding => "transcodingEnableHardwareEncoding", Wording::Unkeyed,
    TranscodingEncodingFormatHelp => "transcodingEncodingFormatHelp", Wording::Unkeyed,
    TranscodingAllowHevc => "transcodingAllowHevc", Wording::Unkeyed,
    TranscodingTonemapping => "transcodingTonemapping", Wording::Unkeyed,
    TranscodingTonemappingHelp => "transcodingTonemappingHelp", Wording::Unkeyed,
    TranscodingThreadCount => "transcodingThreadCount", Wording::Unkeyed,
    TranscodingThreadCountHelp => "transcodingThreadCountHelp", Wording::Unkeyed,
    TranscodingPath => "transcodingPath", Wording::Unkeyed,
    TranscodingPathHelp => "transcodingPathHelp", Wording::Unkeyed,
    TranscodingDownMixBoost => "transcodingDownMixBoost", Wording::Unkeyed,
    TranscodingDownMixBoostHelp => "transcodingDownMixBoostHelp", Wording::Unkeyed,
    TranscodingThrottle => "transcodingThrottle", Wording::Unkeyed,
    TranscodingThrottleHelp => "transcodingThrottleHelp", Wording::Unkeyed,
    TranscodingThrottleDelay => "transcodingThrottleDelay", Wording::Unkeyed,
    TranscodingThrottleDelayHelp => "transcodingThrottleDelayHelp", Wording::Unkeyed,
    TrickplayHardwareDecoding => "trickplayHardwareDecoding", Wording::Unkeyed,
    TrickplayHardwareEncoding => "trickplayHardwareEncoding", Wording::Unkeyed,
    TrickplayHardwareEncodingHelp => "trickplayHardwareEncodingHelp", Wording::Unkeyed,
    TrickplayInterval => "trickplayInterval", Wording::Unkeyed,
    TrickplayIntervalHelp => "trickplayIntervalHelp", Wording::Unkeyed,
    TrickplayTileWidth => "trickplayTileWidth", Wording::Unkeyed,
    TrickplayTileWidthHelp => "trickplayTileWidthHelp", Wording::Unkeyed,
    TrickplayTileHeight => "trickplayTileHeight", Wording::Unkeyed,
    TrickplayTileHeightHelp => "trickplayTileHeightHelp", Wording::Unkeyed,
    TrickplayJpegQuality => "trickplayJpegQuality", Wording::Unkeyed,
    TrickplayJpegQualityHelp => "trickplayJpegQualityHelp", Wording::Unkeyed,
    TrickplayQscale => "trickplayQscale", Wording::Unkeyed,
    TrickplayQscaleHelp => "trickplayQscaleHelp", Wording::Unkeyed,
    TrickplayThreads => "trickplayThreads", Wording::Unkeyed,
    TrickplayThreadsHelp => "trickplayThreadsHelp", Wording::Unkeyed,
    DashboardSave => "dashboardSave", Wording::Unkeyed,
    DashboardSaved => "dashboardSaved", Wording::Unkeyed,
    DashboardUnsaved => "dashboardUnsaved", Wording::Unkeyed,
    DashboardLeaveAnyway => "dashboardLeaveAnyway", Wording::Unkeyed,
    DashboardStayHere => "dashboardStayHere", Wording::Unkeyed,
    NavSettings => "navSettings", Wording::Reference(Sentence::Settings),
    SettingsTitle => "settingsTitle", Wording::Unkeyed,
    SettingsProfile => "settingsProfile", Wording::Unkeyed,
    SettingsDisplay => "settingsDisplay", Wording::Unkeyed,
    SettingsHome => "settingsHome", Wording::Unkeyed,
    SettingsPlayback => "settingsPlayback", Wording::Unkeyed,
    SettingsSubtitles => "settingsSubtitles", Wording::Unkeyed,
    SettingsControls => "settingsControls", Wording::Unkeyed,
    SettingsQuickConnect => "settingsQuickConnect", Wording::Unkeyed,
    SettingsSave => "settingsSave", Wording::Unkeyed,
    SettingsServerChanged => "settingsServerChanged", Wording::Unkeyed,
    ProfileAdministrator => "profileAdministrator", Wording::Unkeyed,
    ProfileMember => "profileMember", Wording::Unkeyed,
    ProfileLastActive => "profileLastActive", Wording::Unkeyed,
    ProfileDisplayName => "profileDisplayName", Wording::Unkeyed,
    ProfileSaveName => "profileSaveName", Wording::Unkeyed,
    ProfileImage => "profileImage", Wording::Unkeyed,
    ProfileImageChoose => "profileImageChoose", Wording::Unkeyed,
    PasswordCurrent => "passwordCurrent", Wording::Unkeyed,
    PasswordNew => "passwordNew", Wording::Unkeyed,
    PasswordChange => "passwordChange", Wording::Unkeyed,
    PasswordOtherDevices => "passwordOtherDevices", Wording::Unkeyed,
    DisplayMissingEpisodes => "displayMissingEpisodes", Wording::Unkeyed,
    DisplayMissingEpisodesHelp => "displayMissingEpisodesHelp", Wording::Unkeyed,
    HomeOrder => "homeOrder", Wording::Unkeyed,
    MoveUp => "moveUp", Wording::Unkeyed,
    MoveDown => "moveDown", Wording::Unkeyed,
    HomeInMyMedia => "homeInMyMedia", Wording::Unkeyed,
    HomeContinueWatchingRow => "homeContinueWatchingRow", Wording::Unkeyed,
    HomeNextUpRow => "homeNextUpRow", Wording::Unkeyed,
    PlaybackAudioLanguage => "playbackAudioLanguage", Wording::Unkeyed,
    PlaybackSubtitleLanguage => "playbackSubtitleLanguage", Wording::Unkeyed,
    PlaybackLanguageAny => "playbackLanguageAny", Wording::Unkeyed,
    PlaybackDefaultAudioTrack => "playbackDefaultAudioTrack", Wording::Unkeyed,
    PlaybackSubtitleMode => "playbackSubtitleMode", Wording::Unkeyed,
    PlaybackSubtitleModeDefault => "playbackSubtitleModeDefault", Wording::Unkeyed,
    PlaybackSubtitleModeDefaultHelp => "playbackSubtitleModeDefaultHelp", Wording::Unkeyed,
    PlaybackSubtitleModeAlways => "playbackSubtitleModeAlways", Wording::Unkeyed,
    PlaybackSubtitleModeAlwaysHelp => "playbackSubtitleModeAlwaysHelp", Wording::Unkeyed,
    PlaybackSubtitleModeOnlyForced => "playbackSubtitleModeOnlyForced", Wording::Unkeyed,
    PlaybackSubtitleModeOnlyForcedHelp => "playbackSubtitleModeOnlyForcedHelp", Wording::Unkeyed,
    PlaybackSubtitleModeNone => "playbackSubtitleModeNone", Wording::Unkeyed,
    PlaybackSubtitleModeNoneHelp => "playbackSubtitleModeNoneHelp", Wording::Unkeyed,
    PlaybackSubtitleModeSmart => "playbackSubtitleModeSmart", Wording::Unkeyed,
    PlaybackSubtitleModeSmartHelp => "playbackSubtitleModeSmartHelp", Wording::Unkeyed,
    PlaybackNextEpisode => "playbackNextEpisode", Wording::Unkeyed,
    PlaybackQuality => "playbackQuality", Wording::Unkeyed,
    PlaybackSkipBack => "playbackSkipBack", Wording::Unkeyed,
    PlaybackSkipForward => "playbackSkipForward", Wording::Unkeyed,
    PlaybackSeconds => "playbackSeconds", Wording::Unkeyed,
    PlaybackSyncPlay => "playbackSyncPlay", Wording::Unkeyed,
    PlaybackSyncOffset => "playbackSyncOffset", Wording::Unkeyed,
    PlaybackSyncMilliseconds => "playbackSyncMilliseconds", Wording::Unkeyed,
    PlaybackSyncMethod => "playbackSyncMethod", Wording::Unkeyed,
    PlaybackSyncMethodAuto => "playbackSyncMethodAuto", Wording::Unkeyed,
    PlaybackSyncMethodRate => "playbackSyncMethodRate", Wording::Unkeyed,
    PlaybackSyncMethodSeek => "playbackSyncMethodSeek", Wording::Unkeyed,
    PlaybackSyncRateAttempts => "playbackSyncRateAttempts", Wording::Unkeyed,
    PlaybackSyncSeekAttempts => "playbackSyncSeekAttempts", Wording::Unkeyed,
    SubtitlesSize => "subtitlesSize", Wording::Unkeyed,
    SubtitlesColour => "subtitlesColour", Wording::Unkeyed,
    SubtitlesBackground => "subtitlesBackground", Wording::Unkeyed,
    SubtitlesOpacity => "subtitlesOpacity", Wording::Unkeyed,
    SubtitlesShadow => "subtitlesShadow", Wording::Unkeyed,
    SubtitlesBurnedIn => "subtitlesBurnedIn", Wording::Unkeyed,
    SubtitleSizeSmall => "subtitleSizeSmall", Wording::Unkeyed,
    SubtitleSizeMedium => "subtitleSizeMedium", Wording::Unkeyed,
    SubtitleSizeLarge => "subtitleSizeLarge", Wording::Unkeyed,
    SubtitleSizeHuge => "subtitleSizeHuge", Wording::Unkeyed,
    ColourWhite => "colourWhite", Wording::Unkeyed,
    ColourBlack => "colourBlack", Wording::Unkeyed,
    ColourRed => "colourRed", Wording::Unkeyed,
    ColourGreen => "colourGreen", Wording::Unkeyed,
    ColourBlue => "colourBlue", Wording::Unkeyed,
    ColourYellow => "colourYellow", Wording::Unkeyed,
    ColourMagenta => "colourMagenta", Wording::Unkeyed,
    ColourCyan => "colourCyan", Wording::Unkeyed,
    ShadowNone => "shadowNone", Wording::Unkeyed,
    ShadowDrop => "shadowDrop", Wording::Unkeyed,
    ShadowOutline => "shadowOutline", Wording::Unkeyed,
    KeySpace => "keySpace", Wording::Unkeyed,
    KeyK => "keyK", Wording::Unkeyed,
    KeyF => "keyF", Wording::Unkeyed,
    KeyM => "keyM", Wording::Unkeyed,
    KeyN => "keyN", Wording::Unkeyed,
    KeyP => "keyP", Wording::Unkeyed,
    KeyEscape => "keyEscape", Wording::Unkeyed,
    KeyArrowLeft => "keyArrowLeft", Wording::Unkeyed,
    KeyArrowRight => "keyArrowRight", Wording::Unkeyed,
    KeyArrowUp => "keyArrowUp", Wording::Unkeyed,
    KeyArrowDown => "keyArrowDown", Wording::Unkeyed,
    DoesTogglePlay => "doesTogglePlay", Wording::Unkeyed,
    DoesSkipBack => "doesSkipBack", Wording::Unkeyed,
    DoesSkipForward => "doesSkipForward", Wording::Unkeyed,
    DoesVolumeUp => "doesVolumeUp", Wording::Unkeyed,
    DoesVolumeDown => "doesVolumeDown", Wording::Unkeyed,
    DoesToggleMute => "doesToggleMute", Wording::Unkeyed,
    DoesFullscreen => "doesFullscreen", Wording::Unkeyed,
    DoesNext => "doesNext", Wording::Unkeyed,
    DoesPrevious => "doesPrevious", Wording::Unkeyed,
    DoesLeave => "doesLeave", Wording::Unkeyed,
    QuickConnectDescription => "quickConnectDescription", Wording::Unkeyed,
    QuickConnectCode => "quickConnectCode", Wording::Unkeyed,
    QuickConnectAuthorize => "quickConnectAuthorize", Wording::Unkeyed,
    QuickConnectAuthorized => "quickConnectAuthorized", Wording::Unkeyed,
    ConfirmAuthorizeQuickConnect => "confirmAuthorizeQuickConnect", Wording::Unkeyed,
    FailureQuickConnectUnknown => "failureQuickConnectUnknown", Wording::Unkeyed,
    FailureQuickConnectExpired => "failureQuickConnectExpired", Wording::Unkeyed,
    FailureQuickConnectUsed => "failureQuickConnectUsed", Wording::Unkeyed,
    FailureQuickConnectDisabled => "failureQuickConnectDisabled", Wording::Unkeyed,
    FailureQuickConnectShape => "failureQuickConnectShape", Wording::Unkeyed,
    FailureImageType => "failureImageType", Wording::Unkeyed,
    FailureImageTooLarge => "failureImageTooLarge", Wording::Unkeyed,
    FailureWroteUserName => "failureWroteUserName", Wording::Unkeyed,
    FailureWroteUserConfiguration => "failureWroteUserConfiguration", Wording::Unkeyed,
    FailureWrotePreferences => "failureWrotePreferences", Wording::Unkeyed,
    FailureWroteQuickConnect => "failureWroteQuickConnect", Wording::Unkeyed,
    ConfirmRestart => "confirmRestart", Wording::Unkeyed,
    ConfirmShutdown => "confirmShutdown", Wording::Unkeyed,
    FailureWroteConfiguration => "failureWroteConfiguration", Wording::Unkeyed,
    FailureWroteScan => "failureWroteScan", Wording::Unkeyed,
    FailureWroteRestart => "failureWroteRestart", Wording::Unkeyed,
    FailureWroteShutdown => "failureWroteShutdown", Wording::Unkeyed,
    UsersTitle => "usersTitle", Wording::Unkeyed,
    UsersAdd => "usersAdd", Wording::Unkeyed,
    UsersDelete => "usersDelete", Wording::Unkeyed,
    UsersName => "usersName", Wording::Unkeyed,
    UsersPassword => "usersPassword", Wording::Unkeyed,
    UsersProfile => "usersProfile", Wording::Unkeyed,
    UsersAccess => "usersAccess", Wording::Unkeyed,
    UsersParental => "usersParental", Wording::Unkeyed,
    UsersImageUpload => "usersImageUpload", Wording::Unkeyed,
    UsersImageRemove => "usersImageRemove", Wording::Unkeyed,
    UsersLastSeen => "usersLastSeen", Wording::Unkeyed,
    UsersOwnAdministrator => "usersOwnAdministrator", Wording::Unkeyed,
    UsersRemoteAccess => "usersRemoteAccess", Wording::Unkeyed,
    UsersRemoteAccessHelp => "usersRemoteAccessHelp", Wording::Unkeyed,
    UsersAdministrator => "usersAdministrator", Wording::Unkeyed,
    UsersFeatureAccess => "usersFeatureAccess", Wording::Unkeyed,
    UsersLiveTvAccess => "usersLiveTvAccess", Wording::Unkeyed,
    UsersLiveTvManagement => "usersLiveTvManagement", Wording::Unkeyed,
    UsersPlayback => "usersPlayback", Wording::Unkeyed,
    UsersMediaPlayback => "usersMediaPlayback", Wording::Unkeyed,
    UsersAudioTranscoding => "usersAudioTranscoding", Wording::Unkeyed,
    UsersVideoTranscoding => "usersVideoTranscoding", Wording::Unkeyed,
    UsersRemuxing => "usersRemuxing", Wording::Unkeyed,
    UsersPlaybackHelp => "usersPlaybackHelp", Wording::Unkeyed,
    UsersBitrateLimit => "usersBitrateLimit", Wording::Unkeyed,
    UsersBitrateLimitHelp => "usersBitrateLimitHelp", Wording::Unkeyed,
    UsersBitrateLimitOverride => "usersBitrateLimitOverride", Wording::Unkeyed,
    UsersSyncPlay => "usersSyncPlay", Wording::Unkeyed,
    UsersSyncPlayHelp => "usersSyncPlayHelp", Wording::Unkeyed,
    UsersSyncPlayCreate => "usersSyncPlayCreate", Wording::Unkeyed,
    UsersSyncPlayJoin => "usersSyncPlayJoin", Wording::Unkeyed,
    UsersSyncPlayNone => "usersSyncPlayNone", Wording::Unkeyed,
    UsersDeletion => "usersDeletion", Wording::Unkeyed,
    UsersDeletionAll => "usersDeletionAll", Wording::Unkeyed,
    UsersOther => "usersOther", Wording::Unkeyed,
    UsersDownloads => "usersDownloads", Wording::Unkeyed,
    UsersDownloadsHelp => "usersDownloadsHelp", Wording::Unkeyed,
    UsersDisabled => "usersDisabled", Wording::Unkeyed,
    UsersDisabledHelp => "usersDisabledHelp", Wording::Unkeyed,
    UsersHidden => "usersHidden", Wording::Unkeyed,
    UsersHiddenHelp => "usersHiddenHelp", Wording::Unkeyed,
    UsersLockout => "usersLockout", Wording::Unkeyed,
    UsersLockoutHelp => "usersLockoutHelp", Wording::Unkeyed,
    UsersLockoutZero => "usersLockoutZero", Wording::Unkeyed,
    UsersSessions => "usersSessions", Wording::Unkeyed,
    UsersSessionsHelp => "usersSessionsHelp", Wording::Unkeyed,
    UsersSessionsZero => "usersSessionsZero", Wording::Unkeyed,
    UsersLibraryAccess => "usersLibraryAccess", Wording::Unkeyed,
    UsersAllLibraries => "usersAllLibraries", Wording::Unkeyed,
    UsersLibraries => "usersLibraries", Wording::Unkeyed,
    UsersLibrariesHelp => "usersLibrariesHelp", Wording::Unkeyed,
    UsersChannelAccess => "usersChannelAccess", Wording::Unkeyed,
    UsersAllChannels => "usersAllChannels", Wording::Unkeyed,
    UsersChannels => "usersChannels", Wording::Unkeyed,
    UsersChannelsHelp => "usersChannelsHelp", Wording::Unkeyed,
    UsersDeviceAccess => "usersDeviceAccess", Wording::Unkeyed,
    UsersAllDevices => "usersAllDevices", Wording::Unkeyed,
    UsersDevices => "usersDevices", Wording::Unkeyed,
    UsersDevicesHelp => "usersDevicesHelp", Wording::Unkeyed,
    UsersMaxRating => "usersMaxRating", Wording::Unkeyed,
    UsersMaxRatingHelp => "usersMaxRatingHelp", Wording::Unkeyed,
    UsersAllowedTags => "usersAllowedTags", Wording::Unkeyed,
    UsersAllowedTagsHelp => "usersAllowedTagsHelp", Wording::Unkeyed,
    UsersBlockedTags => "usersBlockedTags", Wording::Unkeyed,
    UsersBlockedTagsHelp => "usersBlockedTagsHelp", Wording::Unkeyed,
    LibrariesTitle => "librariesTitle", Wording::Unkeyed,
    LibrariesCreate => "librariesCreate", Wording::Unkeyed,
    LibrariesRename => "librariesRename", Wording::Unkeyed,
    LibrariesRemove => "librariesRemove", Wording::Unkeyed,
    LibrariesFolders => "librariesFolders", Wording::Unkeyed,
    LibrariesPathAdd => "librariesPathAdd", Wording::Unkeyed,
    LibrariesPathRemove => "librariesPathRemove", Wording::Unkeyed,
    LibrariesBrowse => "librariesBrowse", Wording::Unkeyed,
    LibrariesManage => "librariesManage", Wording::Unkeyed,
    LibrariesScan => "librariesScan", Wording::Unkeyed,
    LibrariesScanning => "librariesScanning", Wording::Unkeyed,
    LibrariesSettings => "librariesSettings", Wording::Unkeyed,
    LibrariesMetadataLanguage => "librariesMetadataLanguage", Wording::Unkeyed,
    LibrariesMetadataCountry => "librariesMetadataCountry", Wording::Unkeyed,
    LibrariesPhotos => "librariesPhotos", Wording::Unkeyed,
    LibrariesPhotosHelp => "librariesPhotosHelp", Wording::Unkeyed,
    LibrariesRealtimeMonitor => "librariesRealtimeMonitor", Wording::Unkeyed,
    LibrariesRealtimeMonitorHelp => "librariesRealtimeMonitorHelp", Wording::Unkeyed,
    LibrariesMetadataReaders => "librariesMetadataReaders", Wording::Unkeyed,
    LibrariesMetadataReadersHelp => "librariesMetadataReadersHelp", Wording::Unkeyed,
    LibrariesSaveArtwork => "librariesSaveArtwork", Wording::Unkeyed,
    LibrariesSaveArtworkHelp => "librariesSaveArtworkHelp", Wording::Unkeyed,
    LibrariesChapterImages => "librariesChapterImages", Wording::Unkeyed,
    LibrariesChapterExtraction => "librariesChapterExtraction", Wording::Unkeyed,
    LibrariesChapterExtractionHelp => "librariesChapterExtractionHelp", Wording::Unkeyed,
    LibrariesSubtitleDownloads => "librariesSubtitleDownloads", Wording::Unkeyed,
    LibrariesDownloadLanguages => "librariesDownloadLanguages", Wording::Unkeyed,
    LibrariesSubtitleDownloaders => "librariesSubtitleDownloaders", Wording::Unkeyed,
    LibrariesSubtitleDownloadersHelp => "librariesSubtitleDownloadersHelp", Wording::Unkeyed,
    LibrariesSaveSubtitles => "librariesSaveSubtitles", Wording::Unkeyed,
    LibrariesSaveSubtitlesHelp => "librariesSaveSubtitlesHelp", Wording::Unkeyed,
    ConfirmDeleteUser => "confirmDeleteUser", Wording::Unkeyed,
    ConfirmDeleteLibrary => "confirmDeleteLibrary", Wording::Unkeyed,
    ConfirmDeletePath => "confirmDeletePath", Wording::Unkeyed,
    ConfirmRemoveUserImage => "confirmRemoveUserImage", Wording::Unkeyed,
    FailureWroteCollectionCreate => "failureWroteCollectionCreate", Wording::Unkeyed,
    FailureWrotePlaylistCreate => "failureWrotePlaylistCreate", Wording::Unkeyed,
    FailureWrotePlaylistRename => "failureWrotePlaylistRename", Wording::Unkeyed,
    FailureWrotePlaylistDelete => "failureWrotePlaylistDelete", Wording::Unkeyed,
    FailureWrotePlaylistRemove => "failureWrotePlaylistRemove", Wording::Unkeyed,
    FailureWrotePlaylistMove => "failureWrotePlaylistMove", Wording::Unkeyed,
    FailureWrotePlaylistShare => "failureWrotePlaylistShare", Wording::Unkeyed,
    FailureWroteCollectionAdd => "failureWroteCollectionAdd", Wording::Unkeyed,
    FailureWroteCollectionRemove => "failureWroteCollectionRemove", Wording::Unkeyed,
    FailureWrotePlaylistAdd => "failureWrotePlaylistAdd", Wording::Unkeyed,
    OverflowMarkPlayed => "overflowMarkPlayed", Wording::Unkeyed,
    OverflowMarkUnplayed => "overflowMarkUnplayed", Wording::Unkeyed,
    OverflowFavorite => "overflowFavorite", Wording::Unkeyed,
    OverflowUnfavorite => "overflowUnfavorite", Wording::Unkeyed,
    OverflowAddToCollection => "overflowAddToCollection", Wording::Unkeyed,
    OverflowAddToPlaylist => "overflowAddToPlaylist", Wording::Unkeyed,
    OverflowRemoveFromCollection => "overflowRemoveFromCollection", Wording::Unkeyed,
    OverflowCreateAndFile => "overflowCreateAndFile", Wording::Unkeyed,
    OverflowOpen => "overflowOpen", Wording::Unkeyed,
    MenuPlay => "menuPlay", Wording::Unkeyed,
    MenuDeleteMedia => "menuDeleteMedia", Wording::Unkeyed,
    MenuCancelRecording => "menuCancelRecording", Wording::Unkeyed,
    MenuCancelSeries => "menuCancelSeries", Wording::Unkeyed,
    ConfirmCancelRecording => "confirmCancelRecording", Wording::Unkeyed,
    ConfirmCancelSeries => "confirmCancelSeries", Wording::Unkeyed,
    SheetCancel => "sheetCancel", Wording::Unkeyed,
    SheetPlayOn => "sheetPlayOn", Wording::Unkeyed,
    SheetSelectGroup => "sheetSelectGroup", Wording::Unkeyed,
    SheetNewGroup => "sheetNewGroup", Wording::Unkeyed,
    SheetNewGroupHelp => "sheetNewGroupHelp", Wording::Unkeyed,
    SheetHaltPlayback => "sheetHaltPlayback", Wording::Unkeyed,
    SheetHaltPlaybackHelp => "sheetHaltPlaybackHelp", Wording::Unkeyed,
    SheetLeaveGroup => "sheetLeaveGroup", Wording::Unkeyed,
    SheetLeaveGroupHelp => "sheetLeaveGroupHelp", Wording::Unkeyed,
    CardPlay => "cardPlay", Wording::Unkeyed,
    CardMarkPlayed => "cardMarkPlayed", Wording::Unkeyed,
    CardWatched => "cardWatched", Wording::Unkeyed,
    CardAddToFavorites => "cardAddToFavorites", Wording::Unkeyed,
    CardFavorite => "cardFavorite", Wording::Unkeyed,
    CardSpecialEpisode => "cardSpecialEpisode", Wording::Reference(Sentence::ValueSpecialEpisodeName),
    FailureWroteUserCreate => "failureWroteUserCreate", Wording::Unkeyed,
    FailureWroteUserSave => "failureWroteUserSave", Wording::Unkeyed,
    FailureWroteUserDelete => "failureWroteUserDelete", Wording::Unkeyed,
    FailureWroteUserPassword => "failureWroteUserPassword", Wording::Unkeyed,
    FailureWroteUserImage => "failureWroteUserImage", Wording::Unkeyed,
    FailureWroteLibraryCreate => "failureWroteLibraryCreate", Wording::Unkeyed,
    FailureWroteLibraryRename => "failureWroteLibraryRename", Wording::Unkeyed,
    FailureWroteLibraryDelete => "failureWroteLibraryDelete", Wording::Unkeyed,
    FailureWroteLibraryPath => "failureWroteLibraryPath", Wording::Unkeyed,
    FailureWroteLibraryOptions => "failureWroteLibraryOptions", Wording::Unkeyed,
    Percent => "percent", Wording::Unkeyed,
    TasksTitle => "tasksTitle", Wording::Unkeyed,
    TasksLastRun => "tasksLastRun", Wording::Unkeyed,
    TasksLastRan => "tasksLastRan", Wording::Unkeyed,
    TasksStopping => "tasksStopping", Wording::Unkeyed,
    TasksFailed => "tasksFailed", Wording::Unkeyed,
    TasksCancelled => "tasksCancelled", Wording::Unkeyed,
    TasksAborted => "tasksAborted", Wording::Unkeyed,
    TasksDuration => "tasksDuration", Wording::Unkeyed,
    TasksTriggers => "tasksTriggers", Wording::Unkeyed,
    TasksTriggerDaily => "tasksTriggerDaily", Wording::Unkeyed,
    TasksTriggerInterval => "tasksTriggerInterval", Wording::Unkeyed,
    TasksTriggerStartup => "tasksTriggerStartup", Wording::Unkeyed,
    TasksTriggerRemove => "tasksTriggerRemove", Wording::Unkeyed,
    DistanceLessThanMinute => "distanceLessThanMinute", Wording::Unkeyed,
    DistanceLessThanMinutes => "distanceLessThanMinutes", Wording::Unkeyed,
    DistanceMinute => "distanceMinute", Wording::Unkeyed,
    DistanceMinutes => "distanceMinutes", Wording::Unkeyed,
    DistanceAboutHour => "distanceAboutHour", Wording::Unkeyed,
    DistanceAboutHours => "distanceAboutHours", Wording::Unkeyed,
    DistanceDay => "distanceDay", Wording::Unkeyed,
    DistanceDays => "distanceDays", Wording::Unkeyed,
    DistanceAboutMonth => "distanceAboutMonth", Wording::Unkeyed,
    DistanceAboutMonths => "distanceAboutMonths", Wording::Unkeyed,
    DistanceMonth => "distanceMonth", Wording::Unkeyed,
    DistanceMonths => "distanceMonths", Wording::Unkeyed,
    DistanceAboutYear => "distanceAboutYear", Wording::Unkeyed,
    DistanceAboutYears => "distanceAboutYears", Wording::Unkeyed,
    DistanceOverYear => "distanceOverYear", Wording::Unkeyed,
    DistanceOverYears => "distanceOverYears", Wording::Unkeyed,
    DistanceAlmostYear => "distanceAlmostYear", Wording::Unkeyed,
    DistanceAlmostYears => "distanceAlmostYears", Wording::Unkeyed,
    DistancePassed => "distancePassed", Wording::Unkeyed,
    DistanceAhead => "distanceAhead", Wording::Unkeyed,
    LogsTitle => "logsTitle", Wording::Unkeyed,
    LogsTail => "logsTail", Wording::Unkeyed,
    LogsSlowResponse => "logsSlowResponse", Wording::Unkeyed,
    LogsSlowResponseTime => "logsSlowResponseTime", Wording::Unkeyed,
    LogsMebibytes => "logsMebibytes", Wording::Unkeyed,
    ActivityTitle => "activityTitle", Wording::Unkeyed,
    ActivityWithUser => "activityWithUser", Wording::Unkeyed,
    ActivityWithoutUser => "activityWithoutUser", Wording::Unkeyed,
    ActivityAll => "activityAll", Wording::Unkeyed,
    ConfirmStopTask => "confirmStopTask", Wording::Unkeyed,
    FailureWroteTaskStart => "failureWroteTaskStart", Wording::Unkeyed,
    FailureWroteTaskStop => "failureWroteTaskStop", Wording::Unkeyed,
    FailureWroteTaskTriggers => "failureWroteTaskTriggers", Wording::Unkeyed,
    FailureLogMissing => "failureLogMissing", Wording::Unkeyed,
    CatalogTitle => "catalogTitle", Wording::Unkeyed,
    CatalogInstall => "catalogInstall", Wording::Unkeyed,
    CatalogInstalling => "catalogInstalling", Wording::Unkeyed,
    CatalogCancel => "catalogCancel", Wording::Unkeyed,
    CatalogVersions => "catalogVersions", Wording::Unkeyed,
    RepositoriesTitle => "repositoriesTitle", Wording::Unkeyed,
    RepositoriesAdd => "repositoriesAdd", Wording::Unkeyed,
    RepositoriesRemove => "repositoriesRemove", Wording::Unkeyed,
    RepositoriesUrl => "repositoriesUrl", Wording::Unkeyed,
    RepositoriesEmpty => "repositoriesEmpty", Wording::Unkeyed,
    RepositoriesEmptyHelp => "repositoriesEmptyHelp", Wording::Unkeyed,
    DevicesTitle => "devicesTitle", Wording::Unkeyed,
    DevicesRename => "devicesRename", Wording::Unkeyed,
    KeysTitle => "keysTitle", Wording::Unkeyed,
    KeysHelp => "keysHelp", Wording::Unkeyed,
    ColumnApp => "columnApp", Wording::Unkeyed,
    ColumnDevice => "columnDevice", Wording::Unkeyed,
    ColumnIssued => "columnIssued", Wording::Unkeyed,
    ColumnKey => "columnKey", Wording::Unkeyed,
    ColumnLastActive => "columnLastActive", Wording::Unkeyed,
    ColumnLevel => "columnLevel", Wording::Unkeyed,
    ColumnName => "columnName", Wording::Unkeyed,
    ColumnOverview => "columnOverview", Wording::Unkeyed,
    ColumnTime => "columnTime", Wording::Unkeyed,
    ColumnType => "columnType", Wording::Unkeyed,
    ColumnUser => "columnUser", Wording::Unkeyed,
    KeysApp => "keysApp", Wording::Unkeyed,
    KeysCreate => "keysCreate", Wording::Unkeyed,
    ConfirmInstallPackage => "confirmInstallPackage", Wording::Unkeyed,
    ConfirmAddRepository => "confirmAddRepository", Wording::Unkeyed,
    ConfirmRemoveRepository => "confirmRemoveRepository", Wording::Unkeyed,
    ConfirmDeleteDevice => "confirmDeleteDevice", Wording::Unkeyed,
    ConfirmDeleteOwnDevice => "confirmDeleteOwnDevice", Wording::Unkeyed,
    ConfirmRevokeKey => "confirmRevokeKey", Wording::Unkeyed,
    FailureWrotePackageInstall => "failureWrotePackageInstall", Wording::Unkeyed,
    FailureWrotePackageCancel => "failureWrotePackageCancel", Wording::Unkeyed,
    FailureWroteRepositoryAdd => "failureWroteRepositoryAdd", Wording::Unkeyed,
    FailureWroteRepositoryRemove => "failureWroteRepositoryRemove", Wording::Unkeyed,
    FailureWroteDeviceRename => "failureWroteDeviceRename", Wording::Unkeyed,
    FailureWroteDeviceDelete => "failureWroteDeviceDelete", Wording::Unkeyed,
    FailureWroteKeyCreate => "failureWroteKeyCreate", Wording::Unkeyed,
    FailureWroteKeyRevoke => "failureWroteKeyRevoke", Wording::Unkeyed,
    FailureOwnDeviceDeleted => "failureOwnDeviceDeleted", Wording::Unkeyed,
    FailureDemoted => "failureDemoted", Wording::Unkeyed,
    TunersTitle => "tunersTitle", Wording::Unkeyed,
    TunersAdd => "tunersAdd", Wording::Unkeyed,
    TunersDelete => "tunersDelete", Wording::Unkeyed,
    TunersDiscover => "tunersDiscover", Wording::Unkeyed,
    TunersReset => "tunersReset", Wording::Unkeyed,
    TunersUrl => "tunersUrl", Wording::Unkeyed,
    ProvidersTitle => "providersTitle", Wording::Unkeyed,
    ProvidersSchedulesDirect => "providersSchedulesDirect", Wording::Unkeyed,
    ProvidersXmltv => "providersXmltv", Wording::Unkeyed,
    ProvidersUsername => "providersUsername", Wording::Unkeyed,
    ProvidersPassword => "providersPassword", Wording::Unkeyed,
    ProvidersPostcode => "providersPostcode", Wording::Unkeyed,
    ProvidersLineup => "providersLineup", Wording::Unkeyed,
    ProvidersPath => "providersPath", Wording::Unkeyed,
    ProvidersAdd => "providersAdd", Wording::Unkeyed,
    ProvidersDelete => "providersDelete", Wording::Unkeyed,
    MappingTitle => "mappingTitle", Wording::Unkeyed,
    DvrTitle => "dvrTitle", Wording::Unkeyed,
    DvrRecordingPath => "dvrRecordingPath", Wording::Unkeyed,
    DvrRecordingPathHelp => "dvrRecordingPathHelp", Wording::Unkeyed,
    DvrMovieRecordingPath => "dvrMovieRecordingPath", Wording::Unkeyed,
    DvrSeriesRecordingPath => "dvrSeriesRecordingPath", Wording::Unkeyed,
    DvrDefaults => "dvrDefaults", Wording::Unkeyed,
    DvrStartWhenPossible => "dvrStartWhenPossible", Wording::Unkeyed,
    DvrMinutesBefore => "dvrMinutesBefore", Wording::Unkeyed,
    DvrStopWhenPossible => "dvrStopWhenPossible", Wording::Unkeyed,
    DvrMinutesAfter => "dvrMinutesAfter", Wording::Unkeyed,
    ConfirmDeleteTuner => "confirmDeleteTuner", Wording::Unkeyed,
    ConfirmDeleteProvider => "confirmDeleteProvider", Wording::Unkeyed,
    FailureWroteTunerAdd => "failureWroteTunerAdd", Wording::Unkeyed,
    FailureWroteTunerDelete => "failureWroteTunerDelete", Wording::Unkeyed,
    FailureWroteTunerReset => "failureWroteTunerReset", Wording::Unkeyed,
    FailureWroteProviderAdd => "failureWroteProviderAdd", Wording::Unkeyed,
    FailureWroteProviderDelete => "failureWroteProviderDelete", Wording::Unkeyed,
    FailureWroteChannelMapping => "failureWroteChannelMapping", Wording::Unkeyed,
    FailureWroteDvr => "failureWroteDvr", Wording::Unkeyed,
    DetailRefreshMetadata => "detailRefreshMetadata", Wording::Unkeyed,
    DetailRefreshReplace => "detailRefreshReplace", Wording::Unkeyed,
    DetailRefreshScanMode => "detailRefreshScanMode", Wording::Unkeyed,
    FailureWroteRefreshItem => "failureWroteRefreshItem", Wording::Unkeyed,
    FailureAdministratorRestarted => "failureAdministratorRestarted", Wording::Unkeyed,
    FailureAdministratorShutDown => "failureAdministratorShutDown", Wording::Unkeyed,
    ServerSaid => "serverSaid", Wording::Unkeyed,
    FailureBodyTooLarge => "failureBodyTooLarge", Wording::Unkeyed,
    FailureBodyOverCap => "failureBodyOverCap", Wording::Unkeyed,
    FailureBridgeVerb => "failureBridgeVerb", Wording::Unkeyed,
    FailurePageNotListed => "failurePageNotListed", Wording::Unkeyed,
    FailurePageNotRewritable => "failurePageNotRewritable", Wording::Unkeyed,
    FailurePageTooLarge => "failurePageTooLarge", Wording::Unkeyed,
    DashboardReadOnly => "dashboardReadOnly", Wording::Unkeyed,
    FailureTimerRefused => "failureTimerRefused", Wording::Unkeyed,
    FailureSeriesTimerRefused => "failureSeriesTimerRefused", Wording::Unkeyed,
    FailureChannelInGroup => "failureChannelInGroup", Wording::Unkeyed,
    FailureActivityDate => "failureActivityDate", Wording::Unkeyed,
    FailureChapterIndex => "failureChapterIndex", Wording::Unkeyed,
    FailureOverlayMount => "failureOverlayMount", Wording::Unkeyed,
    FailureRange => "failureRange", Wording::Unkeyed,
    FailureYear => "failureYear", Wording::Unkeyed,
}

const TABLE_SOURCE: &str = include_str!("../strings/en-us.json");

/// The keys the boot shell reads straight from the table, which no variant
/// names: the shell runs before the wasm module exists.
#[cfg(test)]
const BOOT_KEYS: &[&str] = &["bootLoading", "bootWasmFailed", "bootRetry"];

/// Every key in the order the table writes it, which the parsed map does not
/// carry.
#[cfg(test)]
fn written() -> Vec<&'static str> {
    TABLE_SOURCE
        .lines()
        .filter_map(|line| line.trim_start().strip_prefix('"'))
        .filter_map(|line| line.split_once("\":"))
        .map(|(key, _)| key)
        .collect()
}

fn table() -> &'static serde_json::Map<String, serde_json::Value> {
    static TABLE: OnceLock<serde_json::Map<String, serde_json::Value>> = OnceLock::new();
    TABLE.get_or_init(|| {
        crate::failure::unraised::decoded(TABLE_SOURCE)
            .expect("strings/en-us.json is not a JSON object")
    })
}

/// The sentence `key` reads as; a key the table lacks reads as its own name,
/// which the gate is what prevents.
pub fn lookup(key: Text) -> &'static str {
    table()
        .get(key.key())
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| key.key())
}

pub fn format(key: Text, args: &[&str]) -> String {
    let template = lookup(key);
    let mut out = String::with_capacity(template.len());
    let mut rest = template;
    while let Some(open) = rest.find('{') {
        let Some(close) = rest[open..].find('}').map(|i| open + i) else {
            break;
        };
        let Ok(index) = rest[open + 1..close].parse::<usize>() else {
            out.push_str(&rest[..close + 1]);
            rest = &rest[close + 1..];
            continue;
        };
        out.push_str(&rest[..open]);
        out.push_str(args.get(index).copied().unwrap_or_default());
        rest = &rest[close + 1..];
    }
    out.push_str(rest);
    out
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use wasm_bindgen_test::wasm_bindgen_test;

    use super::{BOOT_KEYS, Text, Wording, written};

    /// The table lists the boot shell's keys, then every variant's key in the
    /// order `text!` declares them, and nothing else.
    #[wasm_bindgen_test]
    fn the_table_holds_every_variant_in_declaration_order() {
        let expected: Vec<&str> = BOOT_KEYS
            .iter()
            .copied()
            .chain(Text::ALL.iter().map(|text| text.key()))
            .collect();
        let held = written();
        let named: HashSet<&str> = expected.iter().copied().collect();
        let carried: HashSet<&str> = held.iter().copied().collect();
        let mut missing: Vec<&str> = named.difference(&carried).copied().collect();
        let mut stray: Vec<&str> = carried.difference(&named).copied().collect();
        missing.sort_unstable();
        stray.sort_unstable();
        assert!(
            missing.is_empty() && stray.is_empty(),
            "the string table lacks {missing:?} and holds {stray:?} under no variant"
        );
        let misplaced = held
            .iter()
            .zip(&expected)
            .find(|(held, wanted)| held != wanted)
            .map(|(held, wanted)| format!("{held} stands where {wanted} belongs"));
        assert!(
            misplaced.is_none(),
            "the string table is out of declaration order: {misplaced:?}"
        );
    }

    /// A variant naming the reference's own key names it as the reference's own
    /// table spells it, which is what lets the key stand as a variant with no
    /// conversion between the two.
    #[wasm_bindgen_test]
    fn every_reference_key_is_spelled_as_the_reference_spells_it() {
        let held: Vec<String> = Text::ALL
            .iter()
            .filter_map(|text| match text.sentence() {
                Wording::Reference(key) => Some(format!("{key:?}")),
                Wording::Unkeyed => None,
            })
            .filter(|key| {
                !key.starts_with(|value: char| value.is_ascii_uppercase())
                    || !key.chars().all(|value| value.is_ascii_alphanumeric())
            })
            .collect();
        assert!(
            held.is_empty(),
            "keys the reference does not spell: {held:?}"
        );
    }
}
