use std::sync::OnceLock;

#[cfg(test)]
use jellium_model::construct::Sentence;

/// Declares the text enum, the roll the gate reads and the key each variant
/// reads under, from one list. A variant named here is in all three; a variant
/// named nowhere else does not exist.
macro_rules! text {
    ($($variant:ident => $key:literal, $wording:expr,)*) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Text {
            $($variant,)*
        }

        impl Text {
            /// Every variant, which is what the string table is checked
            /// against.
            #[cfg(test)]
            pub const ALL: &'static [Text] = &[$(Text::$variant,)*];

            /// The key this text reads under in the string table.
            pub fn key(self) -> &'static str {
                match self {
                    $(Text::$variant => $key,)*
                }
            }

            /// What this sentence stands for, which is what the construct gate
            /// compares against the reference's own key.
            #[cfg(test)]
            pub fn sentence(self) -> Wording {
                match self {
                    $(Text::$variant => $wording,)*
                }
            }
        }
    };
}

/// What a sentence of this client stands for.
#[cfg(test)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Wording {
    /// The reference's own string key this sentence carries.
    Reference(Sentence),
    /// A sentence of this client's own, licensed by a row of
    /// `reference/exemptions.tsv`.
    Own,
}

text! {
    SetupTitle => "setupTitle", Wording::Own,
    SetupPosition => "setupPosition", Wording::Own,
    SetupNext => "setupNext", Wording::Reference(Sentence::Next),
    SetupBack => "setupBack", Wording::Reference(Sentence::ButtonBack),
    SetupResumed => "setupResumed", Wording::Own,
    SetupLanguage => "setupLanguage", Wording::Own,
    SetupLanguageCulture => "setupLanguageCulture", Wording::Own,
    SetupLanguageServerName => "setupLanguageServerName", Wording::Reference(Sentence::LabelServerName),
    SetupLanguageScope => "setupLanguageScope", Wording::Own,
    SetupUser => "setupUser", Wording::Own,
    SetupUserName => "setupUserName", Wording::Own,
    SetupUserPassword => "setupUserPassword", Wording::Reference(Sentence::LabelPassword),
    SetupUserConfirm => "setupUserConfirm", Wording::Own,
    SetupUserMismatch => "setupUserMismatch", Wording::Own,
    SetupLibraries => "setupLibraries", Wording::Reference(Sentence::HeaderLibraries),
    SetupLibrariesEmpty => "setupLibrariesEmpty", Wording::Own,
    SetupLibrariesAdd => "setupLibrariesAdd", Wording::Own,
    SetupLibrariesCancel => "setupLibrariesCancel", Wording::Reference(Sentence::ButtonCancel),
    SetupLibrariesUp => "setupLibrariesUp", Wording::Reference(Sentence::Up),
    SetupMetadata => "setupMetadata", Wording::Own,
    SetupMetadataLanguage => "setupMetadataLanguage", Wording::Reference(Sentence::HeaderPreferredMetadataLanguage),
    SetupMetadataCountry => "setupMetadataCountry", Wording::Own,
    SetupRemoteAccess => "setupRemoteAccess", Wording::Own,
    SetupRemoteAccessEnable => "setupRemoteAccessEnable", Wording::Reference(Sentence::AllowRemoteAccess),
    SetupRemoteAccessPortMapping => "setupRemoteAccessPortMapping", Wording::Own,
    SetupFinish => "setupFinish", Wording::Reference(Sentence::LabelFinish),
    SetupFinishMessage => "setupFinishMessage", Wording::Own,
    SetupFinishAction => "setupFinishAction", Wording::Own,
    LibrariesContentMovies => "librariesContentMovies", Wording::Reference(Sentence::Movies),
    LibrariesContentShows => "librariesContentShows", Wording::Reference(Sentence::Shows),
    LibrariesContentMusic => "librariesContentMusic", Wording::Reference(Sentence::TabMusic),
    LibrariesContentMusicVideos => "librariesContentMusicVideos", Wording::Reference(Sentence::MusicVideos),
    LibrariesContentHomeVideos => "librariesContentHomeVideos", Wording::Reference(Sentence::HomeVideosPhotos),
    LibrariesContentCollections => "librariesContentCollections", Wording::Reference(Sentence::Collections),
    LibrariesContentBooks => "librariesContentBooks", Wording::Reference(Sentence::Books),
    LibrariesContentMixed => "librariesContentMixed", Wording::Own,
    LibrariesContentOther => "librariesContentOther", Wording::Reference(Sentence::Other),
    FailureSetupReadOnly => "failureSetupReadOnly", Wording::Own,
    FailureSetupFinished => "failureSetupFinished", Wording::Own,
    FailureSetupSignIn => "failureSetupSignIn", Wording::Own,
    FailureStageSetupOnly => "failureStageSetupOnly", Wording::Own,
    FailureStageSignedOnly => "failureStageSignedOnly", Wording::Own,
    FailureWroteSetupStep => "failureWroteSetupStep", Wording::Own,
    AppName => "appName", Wording::Own,
    BootNoBackend => "bootNoBackend", Wording::Own,
    BootNoViewport => "bootNoViewport", Wording::Own,
    BootPanicked => "bootPanicked", Wording::Own,
    LoginHeader => "loginHeader", Wording::Reference(Sentence::HeaderPleaseSignIn),
    LoginUsername => "loginUsername", Wording::Reference(Sentence::LabelUsername),
    LoginPassword => "loginPassword", Wording::Reference(Sentence::LabelPassword),
    LoginSubmit => "loginSubmit", Wording::Reference(Sentence::ButtonSignIn),
    LoginWorking => "loginWorking", Wording::Own,
    LoginManual => "loginManual", Wording::Reference(Sentence::ButtonManualLogin),
    LoginCancel => "loginCancel", Wording::Reference(Sentence::ButtonCancel),
    NavSwitch => "navSwitch", Wording::Reference(Sentence::SelectServer),
    LoginServersTitle => "loginServersTitle", Wording::Own,
    LoginServersActive => "loginServersActive", Wording::Own,
    LoginServersSignedIn => "loginServersSignedIn", Wording::Own,
    LoginServersRemove => "loginServersRemove", Wording::Reference(Sentence::ButtonRemove),
    LoginServersAdd => "loginServersAdd", Wording::Own,
    LoginAddTitle => "loginAddTitle", Wording::Own,
    LoginAddUrl => "loginAddUrl", Wording::Reference(Sentence::TabServer),
    LoginAddUrlHelp => "loginAddUrlHelp", Wording::Own,
    LoginAddSubmit => "loginAddSubmit", Wording::Reference(Sentence::Connect),
    LoginAddWorking => "loginAddWorking", Wording::Own,
    LoginBack => "loginBack", Wording::Reference(Sentence::ButtonBack),
    LoginQuickConnect => "loginQuickConnect", Wording::Own,
    LoginQuickConnectTitle => "loginQuickConnectTitle", Wording::Reference(Sentence::QuickConnect),
    LoginQuickConnectInstruction => "loginQuickConnectInstruction", Wording::Own,
    LoginQuickConnectCode => "loginQuickConnectCode", Wording::Own,
    LoginQuickConnectWaiting => "loginQuickConnectWaiting", Wording::Own,
    LoginQuickConnectRetry => "loginQuickConnectRetry", Wording::Own,
    LoginForgotPassword => "loginForgotPassword", Wording::Reference(Sentence::ButtonForgotPassword),
    LoginResetTitle => "loginResetTitle", Wording::Own,
    LoginResetUsername => "loginResetUsername", Wording::Reference(Sentence::LabelUsername),
    LoginResetHelp => "loginResetHelp", Wording::Own,
    LoginResetSubmit => "loginResetSubmit", Wording::Own,
    LoginResetPinWritten => "loginResetPinWritten", Wording::Own,
    LoginResetPinFile => "loginResetPinFile", Wording::Own,
    LoginResetExpires => "loginResetExpires", Wording::Own,
    LoginResetPin => "loginResetPin", Wording::Own,
    LoginResetPinSubmit => "loginResetPinSubmit", Wording::Own,
    LoginResetContactAdministrator => "loginResetContactAdministrator", Wording::Own,
    LoginResetInNetwork => "loginResetInNetwork", Wording::Own,
    LoginResetCleared => "loginResetCleared", Wording::Own,
    FailureThrew => "failureThrew", Wording::Own,
    FailureFontCoverage => "failureFontCoverage", Wording::Own,
    FailureFontFamily => "failureFontFamily", Wording::Own,
    FailureFontUnpacked => "failureFontUnpacked", Wording::Own,
    FailureFontUnread => "failureFontUnread", Wording::Own,
    FailureStored => "failureStored", Wording::Own,
    FailureTouchPoints => "failureTouchPoints", Wording::Own,
    FailureScreenSize => "failureScreenSize", Wording::Own,
    FailureSpeakerCount => "failureSpeakerCount", Wording::Own,
    FailureFullscreen => "failureFullscreen", Wording::Own,
    FailureBeacon => "failureBeacon", Wording::Own,
    FailureLiveNoUrl => "failureLiveNoUrl", Wording::Own,
    FailureLiveNoWindow => "failureLiveNoWindow", Wording::Own,
    FailureLiveNoRetry => "failureLiveNoRetry", Wording::Own,
    FailureLiveFrame => "failureLiveFrame", Wording::Own,
    FailureSocketClosed => "failureSocketClosed", Wording::Own,
    FailureFileUnreadable => "failureFileUnreadable", Wording::Own,
    FailureFileUndecodable => "failureFileUndecodable", Wording::Own,
    FailurePlayerFrame => "failurePlayerFrame", Wording::Own,
    FailureBridgeAnswer => "failureBridgeAnswer", Wording::Own,
    FailureLiveTvSection => "failureLiveTvSection", Wording::Own,
    FailureChannelsUnread => "failureChannelsUnread", Wording::Own,
    FailureLoginLeft => "failureLoginLeft", Wording::Own,
    FailureQuickConnectAbandoned => "failureQuickConnectAbandoned", Wording::Own,
    FailureSessionUnread => "failureSessionUnread", Wording::Own,
    FailureGroupUnresolved => "failureGroupUnresolved", Wording::Own,
    FailurePlaybackUnplanned => "failurePlaybackUnplanned", Wording::Own,
    FailureSetupUnfinished => "failureSetupUnfinished", Wording::Own,
    FailureMarkUnwritten => "failureMarkUnwritten", Wording::Own,
    FailurePreferencesUnmigrated => "failurePreferencesUnmigrated", Wording::Own,
    FailureLiveReport => "failureLiveReport", Wording::Own,
    FailurePluginPageRelease => "failurePluginPageRelease", Wording::Own,
    FailureMediaSession => "failureMediaSession", Wording::Own,
    BootSessionStalled => "bootSessionStalled", Wording::Own,
    BootRecheck => "bootRecheck", Wording::Own,
    FailureActivityUnread => "failureActivityUnread", Wording::Own,
    FailureAiringsUnread => "failureAiringsUnread", Wording::Own,
    FailureBrowseUnread => "failureBrowseUnread", Wording::Own,
    FailureCollectionsUnread => "failureCollectionsUnread", Wording::Own,
    FailureConfigurationUnread => "failureConfigurationUnread", Wording::Own,
    FailureDirectoryUnread => "failureDirectoryUnread", Wording::Own,
    FailureDashboardUnread => "failureDashboardUnread", Wording::Own,
    FailureFilingUnread => "failureFilingUnread", Wording::Own,
    FailureGroupItemsUnread => "failureGroupItemsUnread", Wording::Own,
    FailureGuideUnread => "failureGuideUnread", Wording::Own,
    FailureHomeUnread => "failureHomeUnread", Wording::Own,
    FailureMatchesUnread => "failureMatchesUnread", Wording::Own,
    FailureLibraryUnread => "failureLibraryUnread", Wording::Own,
    FailureLiveTvUnread => "failureLiveTvUnread", Wording::Own,
    FailureSignOut => "failureSignOut", Wording::Own,
    FailureMetadataUnread => "failureMetadataUnread", Wording::Own,
    FailurePreferencesUnread => "failurePreferencesUnread", Wording::Own,
    FailurePlaylistUnread => "failurePlaylistUnread", Wording::Own,
    FailurePlaylistsUnread => "failurePlaylistsUnread", Wording::Own,
    FailurePlaybackReport => "failurePlaybackReport", Wording::Own,
    FailurePlaybackUnread => "failurePlaybackUnread", Wording::Own,
    FailureSearchUnread => "failureSearchUnread", Wording::Own,
    FailureSeriesTimerUnread => "failureSeriesTimerUnread", Wording::Own,
    FailureSettingsUnread => "failureSettingsUnread", Wording::Own,
    FailureSetupStep => "failureSetupStep", Wording::Own,
    FailureQuickConnectUnread => "failureQuickConnectUnread", Wording::Own,
    FailureServersUnread => "failureServersUnread", Wording::Own,
    FailureResetPinUnread => "failureResetPinUnread", Wording::Own,
    FailureServerRemove => "failureServerRemove", Wording::Own,
    FailureSignInAgain => "failureSignInAgain", Wording::Own,
    FailureItemUnread => "failureItemUnread", Wording::Own,
    FailureSimilarUnread => "failureSimilarUnread", Wording::Own,
    FailureLatestUnread => "failureLatestUnread", Wording::Own,
    FailureSuggestionsUnread => "failureSuggestionsUnread", Wording::Own,
    FailureRecommendationsUnread => "failureRecommendationsUnread", Wording::Own,
    FailurePeopleUnread => "failurePeopleUnread", Wording::Own,
    FailureStudiosUnread => "failureStudiosUnread", Wording::Own,
    FailureGenresUnread => "failureGenresUnread", Wording::Own,
    FailureFiltersUnread => "failureFiltersUnread", Wording::Own,
    FailureImageUnread => "failureImageUnread", Wording::Own,
    FailureUserImageUnread => "failureUserImageUnread", Wording::Own,
    FailureTrickplayUnread => "failureTrickplayUnread", Wording::Own,
    FailureUsersUnread => "failureUsersUnread", Wording::Own,
    FailureProvidersUnread => "failureProvidersUnread", Wording::Own,
    FailureMappingUnread => "failureMappingUnread", Wording::Own,
    FailureTunerTypesUnread => "failureTunerTypesUnread", Wording::Own,
    FailureTunersUnread => "failureTunersUnread", Wording::Own,
    FailureTunerDiscovery => "failureTunerDiscovery", Wording::Own,
    FailureLineupsUnread => "failureLineupsUnread", Wording::Own,
    FailurePlaylistSharingUnread => "failurePlaylistSharingUnread", Wording::Own,
    FailureItemImagesUnread => "failureItemImagesUnread", Wording::Own,
    FailureImageProvidersUnread => "failureImageProvidersUnread", Wording::Own,
    FailureContentTypesUnread => "failureContentTypesUnread", Wording::Own,
    FailurePluginPageUnread => "failurePluginPageUnread", Wording::Own,
    FailureDismiss => "failureDismiss", Wording::Own,
    FailuresTitle => "failuresTitle", Wording::Own,
    FailuresOpen => "failuresOpen", Wording::Own,
    FailuresEmpty => "failuresEmpty", Wording::Own,
    FailureSavedSignInRejected => "failureSavedSignInRejected", Wording::Own,
    FailureRemoveUnrevoked => "failureRemoveUnrevoked", Wording::Own,
    FailureQuickConnectSignInExpired => "failureQuickConnectSignInExpired", Wording::Own,
    FailureQuickConnectSignInDisabled => "failureQuickConnectSignInDisabled", Wording::Own,
    FailureResetPinRefused => "failureResetPinRefused", Wording::Own,
    FailureLoginMoved => "failureLoginMoved", Wording::Own,
    FailureStageLoginOnly => "failureStageLoginOnly", Wording::Own,
    HomeMyMedia => "homeMyMedia", Wording::Reference(Sentence::HeaderMyMedia),
    HomeLiveTv => "homeLiveTv", Wording::Reference(Sentence::LiveTV),
    HomeContinueWatching => "homeContinueWatching", Wording::Reference(Sentence::HeaderContinueWatching),
    HomeNextUp => "homeNextUp", Wording::Reference(Sentence::NextUp),
    HomeEmptyHeading => "homeEmptyHeading", Wording::Reference(Sentence::MessageNothingHere),
    HomeEmptyAdministrator => "homeEmptyAdministrator", Wording::Reference(Sentence::NoCreatedLibraries),
    HomeEmptyUser => "homeEmptyUser", Wording::Reference(Sentence::AskAdminToCreateLibrary),
    LibrarySort => "librarySort", Wording::Reference(Sentence::Sort),
    SortName => "sortName", Wording::Own,
    SortNameDescending => "sortNameDescending", Wording::Own,
    SortDateAdded => "sortDateAdded", Wording::Reference(Sentence::DateAdded),
    SortReleaseDate => "sortReleaseDate", Wording::Reference(Sentence::ReleaseDate),
    SortCommunityRating => "sortCommunityRating", Wording::Reference(Sentence::CommunityRating),
    SortRandom => "sortRandom", Wording::Reference(Sentence::OptionRandom),
    GridPaging => "gridPaging", Wording::Reference(Sentence::ListPaging),
    FilterIndicator => "filterIndicator", Wording::Own,
    FilterClose => "filterClose", Wording::Own,
    FilterClear => "filterClear", Wording::Own,
    FilterPlayed => "filterPlayed", Wording::Reference(Sentence::Played),
    FilterResumable => "filterResumable", Wording::Reference(Sentence::OptionResumable),
    FilterFavorite => "filterFavorite", Wording::Reference(Sentence::Favorite),
    FilterHasSubtitles => "filterHasSubtitles", Wording::Own,
    FilterHd => "filterHd", Wording::Reference(Sentence::OptionIsHD),
    FilterUhd => "filterUhd", Wording::Own,
    LibraryTabItems => "libraryTabItems", Wording::Reference(Sentence::Items),
    LibraryTabSuggestions => "libraryTabSuggestions", Wording::Reference(Sentence::Suggestions),
    LibraryTabFavorites => "libraryTabFavorites", Wording::Reference(Sentence::Favorites),
    LibraryTabUpcoming => "libraryTabUpcoming", Wording::Reference(Sentence::TabUpcoming),
    LibraryTabEpisodes => "libraryTabEpisodes", Wording::Reference(Sentence::Episodes),
    LibraryTabSongs => "libraryTabSongs", Wording::Reference(Sentence::Songs),
    LibraryTabAlbumArtists => "libraryTabAlbumArtists", Wording::Reference(Sentence::LabelAlbumArtists),
    LibraryTabArtists => "libraryTabArtists", Wording::Reference(Sentence::Artists),
    LibraryTabGenres => "libraryTabGenres", Wording::Reference(Sentence::Genres),
    LibraryTabStudios => "libraryTabStudios", Wording::Reference(Sentence::Studios),
    LibraryTabNetworks => "libraryTabNetworks", Wording::Own,
    SearchPlaceholder => "searchPlaceholder", Wording::Reference(Sentence::Search),
    SearchSuggestions => "searchSuggestions", Wording::Reference(Sentence::Suggestions),
    SearchResultsEmpty => "searchResultsEmpty", Wording::Reference(Sentence::SearchResultsEmpty),
    SearchMovies => "searchMovies", Wording::Reference(Sentence::Movies),
    SearchShows => "searchShows", Wording::Reference(Sentence::Shows),
    SearchEpisodes => "searchEpisodes", Wording::Reference(Sentence::Episodes),
    SearchPlaylists => "searchPlaylists", Wording::Reference(Sentence::Playlists),
    SearchArtists => "searchArtists", Wording::Reference(Sentence::Artists),
    SearchAlbums => "searchAlbums", Wording::Reference(Sentence::Albums),
    SearchSongs => "searchSongs", Wording::Reference(Sentence::Songs),
    SearchVideos => "searchVideos", Wording::Reference(Sentence::HeaderVideos),
    SearchChannels => "searchChannels", Wording::Reference(Sentence::Channels),
    SearchPhotoAlbums => "searchPhotoAlbums", Wording::Reference(Sentence::HeaderPhotoAlbums),
    SearchPhotos => "searchPhotos", Wording::Reference(Sentence::Photos),
    SearchAudioBooks => "searchAudioBooks", Wording::Reference(Sentence::HeaderAudioBooks),
    SearchBooks => "searchBooks", Wording::Reference(Sentence::Books),
    SearchCollections => "searchCollections", Wording::Reference(Sentence::Collections),
    DetailOverview => "detailOverview", Wording::Reference(Sentence::Overview),
    DetailSimilar => "detailSimilar", Wording::Reference(Sentence::HeaderMoreLikeThis),
    DetailSeasons => "detailSeasons", Wording::Reference(Sentence::HeaderSeasons),
    DetailEpisodes => "detailEpisodes", Wording::Reference(Sentence::Episodes),
    DetailTracks => "detailTracks", Wording::Reference(Sentence::HeaderTracks),
    DetailAlbums => "detailAlbums", Wording::Reference(Sentence::Albums),
    DetailItems => "detailItems", Wording::Reference(Sentence::Items),
    DetailMarkPlayed => "detailMarkPlayed", Wording::Reference(Sentence::MarkPlayed),
    DetailMarkUnplayed => "detailMarkUnplayed", Wording::Reference(Sentence::MarkUnplayed),
    DetailFavorite => "detailFavorite", Wording::Reference(Sentence::AddToFavorites),
    DetailUnfavorite => "detailUnfavorite", Wording::Own,
    DetailMoreCommands => "detailMoreCommands", Wording::Reference(Sentence::ButtonMore),
    NavBack => "navBack", Wording::Reference(Sentence::ButtonBack),
    NavHome => "navHome", Wording::Reference(Sentence::Home),
    NavSearch => "navSearch", Wording::Reference(Sentence::Search),
    NavLogout => "navLogout", Wording::Reference(Sentence::ButtonSignOut),
    StatusLoading => "statusLoading", Wording::Own,
    FailureServerUnreachable => "failureServerUnreachable", Wording::Own,
    FailureCredentialsRejected => "failureCredentialsRejected", Wording::Own,
    FailureTokenRejected => "failureTokenRejected", Wording::Own,
    FailureServerBelowMinimum => "failureServerBelowMinimum", Wording::Own,
    FailureRelay => "failureRelay", Wording::Own,
    FailureNotThisBrowser => "failureNotThisBrowser", Wording::Own,
    FailureForeignOrigin => "failureForeignOrigin", Wording::Own,
    FailureNoSession => "failureNoSession", Wording::Own,
    FailureNotRelayed => "failureNotRelayed", Wording::Own,
    WarningOffSnapshot => "warningOffSnapshot", Wording::Own,
    DetailPlay => "detailPlay", Wording::Reference(Sentence::Play),
    DetailResume => "detailResume", Wording::Reference(Sentence::ButtonResume),
    DetailPlayAll => "detailPlayAll", Wording::Reference(Sentence::HeaderPlayAll),
    DetailShuffle => "detailShuffle", Wording::Reference(Sentence::Shuffle),
    DetailInstantMix => "detailInstantMix", Wording::Reference(Sentence::InstantMix),
    PlayerPlay => "playerPlay", Wording::Reference(Sentence::Play),
    PlayerPause => "playerPause", Wording::Reference(Sentence::ButtonPause),
    PlayerSkipBack => "playerSkipBack", Wording::Own,
    PlayerSkipForward => "playerSkipForward", Wording::Own,
    PlayerPrevious => "playerPrevious", Wording::Reference(Sentence::Previous),
    PlayerNext => "playerNext", Wording::Reference(Sentence::Next),
    PlayerMute => "playerMute", Wording::Reference(Sentence::Mute),
    PlayerUnmute => "playerUnmute", Wording::Reference(Sentence::Unmute),
    PlayerFullscreen => "playerFullscreen", Wording::Reference(Sentence::Fullscreen),
    PlayerExitFullscreen => "playerExitFullscreen", Wording::Own,
    PlayerAudio => "playerAudio", Wording::Reference(Sentence::Audio),
    PlayerSubtitles => "playerSubtitles", Wording::Reference(Sentence::Subtitles),
    PlayerSubtitlesOff => "playerSubtitlesOff", Wording::Reference(Sentence::Off),
    PlayerQuality => "playerQuality", Wording::Reference(Sentence::Quality),
    PlayerQualityAuto => "playerQualityAuto", Wording::Reference(Sentence::Auto),
    PlayerQualityLimit => "playerQualityLimit", Wording::Own,
    PlayerChapters => "playerChapters", Wording::Own,
    PlayerVersion => "playerVersion", Wording::Reference(Sentence::LabelVersion),
    PlayerRepeatMode => "playerRepeatMode", Wording::Reference(Sentence::RepeatMode),
    PlayerQueue => "playerQueue", Wording::Own,
    PlayerFavorite => "playerFavorite", Wording::Reference(Sentence::AddToFavorites),
    PlayerUnfavorite => "playerUnfavorite", Wording::Own,
    PlayerLeave => "playerLeave", Wording::Reference(Sentence::ButtonClose),
    PlayerEndsAt => "playerEndsAt", Wording::Reference(Sentence::EndsAtValue),
    PlayerFetching => "playerFetching", Wording::Reference(Sentence::FetchingData),
    PlayerSettings => "playerSettings", Wording::Reference(Sentence::Settings),
    PlayerEpisode => "playerEpisode", Wording::Own,
    PlayerNextItem => "playerNextItem", Wording::Own,
    PlayerDirect => "playerDirect", Wording::Reference(Sentence::DirectPlaying),
    PlayerTranscoding => "playerTranscoding", Wording::Reference(Sentence::Transcoding),
    PlayerTranscodingBurningInSubtitles => "playerTranscodingBurningInSubtitles", Wording::Own,
    QueueTitle => "queueTitle", Wording::Own,
    QueueEmpty => "queueEmpty", Wording::Own,
    QueueRemove => "queueRemove", Wording::Reference(Sentence::ButtonRemove),
    QueueShuffle => "queueShuffle", Wording::Reference(Sentence::Shuffle),
    QueueRepeatOff => "queueRepeatOff", Wording::Own,
    QueueRepeatOne => "queueRepeatOne", Wording::Reference(Sentence::RepeatOne),
    QueueRepeatAll => "queueRepeatAll", Wording::Reference(Sentence::RepeatAll),
    QueueBack => "queueBack", Wording::Own,
    FailureNoMediaSource => "failureNoMediaSource", Wording::Own,
    FailureNoPlayableSource => "failureNoPlayableSource", Wording::Own,
    FailureTranscodeRefused => "failureTranscodeRefused", Wording::Own,
    FailurePlaybackSuperseded => "failurePlaybackSuperseded", Wording::Own,
    FailureNotRelayable => "failureNotRelayable", Wording::Own,
    FailurePlaybackLapsed => "failurePlaybackLapsed", Wording::Own,
    FailureDecode => "failureDecode", Wording::Own,
    FailureStreamDropped => "failureStreamDropped", Wording::Own,
    FailurePlaybackServer => "failurePlaybackServer", Wording::Own,
    FailurePlaybackHlsFatal => "failurePlaybackHlsFatal", Wording::Own,
    FailureManifestNotRewritable => "failureManifestNotRewritable", Wording::Own,
    FailureManifestTooLarge => "failureManifestTooLarge", Wording::Own,
    FailureForeignNotObserved => "failureForeignNotObserved", Wording::Own,
    FailureItemRemoved => "failureItemRemoved", Wording::Own,
    NavCollections => "navCollections", Wording::Reference(Sentence::Collections),
    NavPlaylists => "navPlaylists", Wording::Reference(Sentence::Playlists),
    CollectionCreate => "collectionCreate", Wording::Own,
    PlaylistCreate => "playlistCreate", Wording::Own,
    PlaylistRename => "playlistRename", Wording::Reference(Sentence::ButtonRename),
    PlaylistDelete => "playlistDelete", Wording::Own,
    PlaylistRemove => "playlistRemove", Wording::Reference(Sentence::ButtonRemove),
    PlaylistMoveUp => "playlistMoveUp", Wording::Reference(Sentence::Up),
    PlaylistMoveDown => "playlistMoveDown", Wording::Reference(Sentence::Down),
    PlaylistOpenAccess => "playlistOpenAccess", Wording::Own,
    PlaylistUnshare => "playlistUnshare", Wording::Own,
    FailureWroteItemSave => "failureWroteItemSave", Wording::Own,
    FailureWroteItemDelete => "failureWroteItemDelete", Wording::Own,
    FailureWroteItemContentType => "failureWroteItemContentType", Wording::Own,
    FailureWroteItemIdentify => "failureWroteItemIdentify", Wording::Own,
    FailureWroteItemImageUpload => "failureWroteItemImageUpload", Wording::Own,
    FailureWroteItemImageRemove => "failureWroteItemImageRemove", Wording::Own,
    FailureWroteItemImageMove => "failureWroteItemImageMove", Wording::Own,
    FailureWroteItemImageDownload => "failureWroteItemImageDownload", Wording::Own,
    MetadataPartFields => "metadataPartFields", Wording::Own,
    MetadataPartIdentify => "metadataPartIdentify", Wording::Reference(Sentence::Identify),
    MetadataPartImages => "metadataPartImages", Wording::Reference(Sentence::Images),
    MetadataPartLocks => "metadataPartLocks", Wording::Own,
    MetadataPartContentType => "metadataPartContentType", Wording::Reference(Sentence::LabelContentType),
    MetadataPartDeletion => "metadataPartDeletion", Wording::Reference(Sentence::Delete),
    MetadataSave => "metadataSave", Wording::Reference(Sentence::Save),
    MetadataClose => "metadataClose", Wording::Reference(Sentence::ButtonClose),
    MetadataDelete => "metadataDelete", Wording::Own,
    MetadataDeleteWarning => "metadataDeleteWarning", Wording::Own,
    MetadataLocked => "metadataLocked", Wording::Own,
    MetadataUnlocked => "metadataUnlocked", Wording::Own,
    MetadataPeople => "metadataPeople", Wording::Own,
    MetadataPersonAdd => "metadataPersonAdd", Wording::Own,
    MetadataPersonRemove => "metadataPersonRemove", Wording::Reference(Sentence::ButtonRemove),
    MetadataProviders => "metadataProviders", Wording::Own,
    MetadataIdentifyName => "metadataIdentifyName", Wording::Reference(Sentence::Name),
    MetadataIdentifyYear => "metadataIdentifyYear", Wording::Reference(Sentence::LabelYear),
    MetadataIdentifyProvider => "metadataIdentifyProvider", Wording::Own,
    MetadataIdentifyProviderId => "metadataIdentifyProviderId", Wording::Own,
    MetadataIdentifyRun => "metadataIdentifyRun", Wording::Reference(Sentence::Search),
    MetadataChoose => "metadataChoose", Wording::Own,
    MetadataApply => "metadataApply", Wording::Own,
    MetadataApplyAsk => "metadataApplyAsk", Wording::Own,
    MetadataCancel => "metadataCancel", Wording::Reference(Sentence::ButtonCancel),
    MetadataReplaceImages => "metadataReplaceImages", Wording::Reference(Sentence::ReplaceExistingImages),
    MetadataOpen => "metadataOpen", Wording::Reference(Sentence::EditMetadata),
    ArtworkPrimary => "artworkPrimary", Wording::Reference(Sentence::Primary),
    ArtworkBackdrop => "artworkBackdrop", Wording::Reference(Sentence::Backdrop),
    ArtworkThumb => "artworkThumb", Wording::Reference(Sentence::Thumb),
    ArtworkLogo => "artworkLogo", Wording::Reference(Sentence::Logo),
    ArtworkBanner => "artworkBanner", Wording::Reference(Sentence::Banner),
    ArtworkArt => "artworkArt", Wording::Own,
    ArtworkRemove => "artworkRemove", Wording::Reference(Sentence::ButtonRemove),
    ArtworkMoveEarlier => "artworkMoveEarlier", Wording::Own,
    ArtworkMoveLater => "artworkMoveLater", Wording::Own,
    ArtworkUpload => "artworkUpload", Wording::Own,
    ArtworkSearch => "artworkSearch", Wording::Own,
    ArtworkDownload => "artworkDownload", Wording::Own,
    ConfirmDeleteItem => "confirmDeleteItem", Wording::Own,
    SearchPeople => "searchPeople", Wording::Reference(Sentence::People),
    SearchStudios => "searchStudios", Wording::Reference(Sentence::Studios),
    SearchPrograms => "searchPrograms", Wording::Reference(Sentence::Programs),
    NavRemote => "navRemote", Wording::Reference(Sentence::HeaderDevices),
    LiveUnavailable => "liveUnavailable", Wording::Own,
    PlayerRemote => "playerRemote", Wording::Own,
    PlayerStop => "playerStop", Wording::Reference(Sentence::ButtonStop),
    RemoteTitle => "remoteTitle", Wording::Reference(Sentence::HeaderDevices),
    RemoteEmpty => "remoteEmpty", Wording::Own,
    RemoteLeave => "remoteLeave", Wording::Own,
    RemoteNothingPlaying => "remoteNothingPlaying", Wording::Own,
    RemoteHeading => "remoteHeading", Wording::Own,
    FailureServerRestarting => "failureServerRestarting", Wording::Own,
    FailureServerShuttingDown => "failureServerShuttingDown", Wording::Own,
    FailureUserDeleted => "failureUserDeleted", Wording::Own,
    FailureRemoteTaken => "failureRemoteTaken", Wording::Own,
    FailureRemoteTargetGone => "failureRemoteTargetGone", Wording::Own,
    FailureRemoteControlled => "failureRemoteControlled", Wording::Own,
    FailureUnknownTarget => "failureUnknownTarget", Wording::Own,
    FailureNotDriving => "failureNotDriving", Wording::Own,
    FailureTargetRefused => "failureTargetRefused", Wording::Own,
    NavSyncPlay => "navSyncPlay", Wording::Reference(Sentence::ButtonSyncPlay),
    PlayerSyncPlay => "playerSyncPlay", Wording::Own,
    SyncPlayTitle => "syncPlayTitle", Wording::Reference(Sentence::ButtonSyncPlay),
    SyncPlayEmpty => "syncPlayEmpty", Wording::Own,
    SyncPlayActive => "syncPlayActive", Wording::Own,
    SyncPlayWaiting => "syncPlayWaiting", Wording::Own,
    SyncPlayParticipants => "syncPlayParticipants", Wording::Own,
    SyncPlayStateIdle => "syncPlayStateIdle", Wording::Reference(Sentence::PriorityIdle),
    SyncPlayStateWaiting => "syncPlayStateWaiting", Wording::Own,
    SyncPlayStatePaused => "syncPlayStatePaused", Wording::Own,
    SyncPlayStatePlaying => "syncPlayStatePlaying", Wording::Own,
    SyncPlayNamedForItem => "syncPlayNamedForItem", Wording::Own,
    SyncPlayNamedForUser => "syncPlayNamedForUser", Wording::Reference(Sentence::SyncPlayGroupDefaultTitle),
    SyncPlayLinkDown => "syncPlayLinkDown", Wording::Own,
    FailureGroupLeft => "failureGroupLeft", Wording::Own,
    FailureGroupRemoved => "failureGroupRemoved", Wording::Own,
    FailureGroupRemote => "failureGroupRemote", Wording::Own,
    FailureGroupNotInGroup => "failureGroupNotInGroup", Wording::Own,
    FailureGroupNoSuchGroup => "failureGroupNoSuchGroup", Wording::Own,
    FailureGroupLibraryDenied => "failureGroupLibraryDenied", Wording::Own,
    FailureGroupUnplayable => "failureGroupUnplayable", Wording::Own,
    FailureNotGrouped => "failureNotGrouped", Wording::Own,
    FailureGroupRefused => "failureGroupRefused", Wording::Own,
    FailureRemoteGrouped => "failureRemoteGrouped", Wording::Own,
    FailureDisplacedByPlayback => "failureDisplacedByPlayback", Wording::Own,
    FailureDisplacedByGroup => "failureDisplacedByGroup", Wording::Own,
    HomeOnNow => "homeOnNow", Wording::Reference(Sentence::HeaderOnNow),
    LiveTvTitle => "liveTvTitle", Wording::Reference(Sentence::LiveTV),
    LiveTvTabGuide => "liveTvTabGuide", Wording::Reference(Sentence::Guide),
    LiveTvTabChannels => "liveTvTabChannels", Wording::Reference(Sentence::Channels),
    LiveTvTabRecordings => "liveTvTabRecordings", Wording::Reference(Sentence::Recordings),
    LiveTvTabSchedule => "liveTvTabSchedule", Wording::Reference(Sentence::Schedule),
    LiveTvTabSeries => "liveTvTabSeries", Wording::Reference(Sentence::Series),
    GuideNow => "guideNow", Wording::Own,
    GuideEarlier => "guideEarlier", Wording::Own,
    GuideLater => "guideLater", Wording::Own,
    GuideEmpty => "guideEmpty", Wording::Own,
    GuideBadgeLive => "guideBadgeLive", Wording::Reference(Sentence::Live),
    GuideBadgeNew => "guideBadgeNew", Wording::Reference(Sentence::New),
    GuideBadgePremiere => "guideBadgePremiere", Wording::Reference(Sentence::Premiere),
    GuideBadgeRepeat => "guideBadgeRepeat", Wording::Reference(Sentence::Repeat),
    ChannelsTv => "channelsTv", Wording::Reference(Sentence::TV),
    ChannelsRadio => "channelsRadio", Wording::Own,
    ChannelsEmpty => "channelsEmpty", Wording::Own,
    ChannelFavorite => "channelFavorite", Wording::Own,
    ChannelUnfavorite => "channelUnfavorite", Wording::Own,
    ProgramChannel => "programChannel", Wording::Own,
    ProgramAirtime => "programAirtime", Wording::Own,
    ProgramRecord => "programRecord", Wording::Reference(Sentence::Record),
    ProgramRecordSeries => "programRecordSeries", Wording::Reference(Sentence::RecordSeries),
    ProgramCancelRecording => "programCancelRecording", Wording::Reference(Sentence::CancelRecording),
    ProgramCancelSeries => "programCancelSeries", Wording::Reference(Sentence::CancelSeries),
    RecordingsEmpty => "recordingsEmpty", Wording::Own,
    RecordingsLatest => "recordingsLatest", Wording::Reference(Sentence::HeaderLatestRecordings),
    ScheduleActive => "scheduleActive", Wording::Reference(Sentence::HeaderActiveRecordings),
    ScheduleEmpty => "scheduleEmpty", Wording::Own,
    SeriesTimerAnytime => "seriesTimerAnytime", Wording::Reference(Sentence::Anytime),
    SeriesTimerAllChannels => "seriesTimerAllChannels", Wording::Reference(Sentence::AllChannels),
    SeriesTimerOneChannel => "seriesTimerOneChannel", Wording::Reference(Sentence::OneChannel),
    SeriesEmpty => "seriesEmpty", Wording::Own,
    SeriesEdit => "seriesEdit", Wording::Reference(Sentence::Edit),
    SeriesSave => "seriesSave", Wording::Reference(Sentence::Save),
    SeriesClose => "seriesClose", Wording::Reference(Sentence::ButtonClose),
    SeriesDayPattern => "seriesDayPattern", Wording::Own,
    SeriesDayPatternAny => "seriesDayPatternAny", Wording::Own,
    SeriesDays => "seriesDays", Wording::Own,
    SeriesAnyChannel => "seriesAnyChannel", Wording::Own,
    SeriesAnyTime => "seriesAnyTime", Wording::Own,
    SeriesNewOnly => "seriesNewOnly", Wording::Own,
    SeriesSkipInLibrary => "seriesSkipInLibrary", Wording::Own,
    SeriesKeepUntil => "seriesKeepUntil", Wording::Own,
    SeriesKeepUpTo => "seriesKeepUpTo", Wording::Reference(Sentence::LabelKeepUpTo),
    SeriesPriority => "seriesPriority", Wording::Own,
    SeriesPrePadding => "seriesPrePadding", Wording::Own,
    SeriesPostPadding => "seriesPostPadding", Wording::Own,
    TimerOptions => "timerOptions", Wording::Reference(Sentence::HeaderRecordingOptions),
    TimerStartEarly => "timerStartEarly", Wording::Reference(Sentence::LabelStartWhenPossible),
    TimerStopLate => "timerStopLate", Wording::Reference(Sentence::LabelStopWhenPossible),
    TimerMinutesBefore => "timerMinutesBefore", Wording::Reference(Sentence::MinutesBefore),
    TimerMinutesAfter => "timerMinutesAfter", Wording::Reference(Sentence::MinutesAfter),
    TimerSave => "timerSave", Wording::Reference(Sentence::Save),
    TimerCancelRecording => "timerCancelRecording", Wording::Reference(Sentence::CancelRecording),
    TimerClose => "timerClose", Wording::Reference(Sentence::ButtonClose),
    PlayerLive => "playerLive", Wording::Reference(Sentence::Live),
    PlayerTuning => "playerTuning", Wording::Own,
    PlayerLiveEdge => "playerLiveEdge", Wording::Own,
    PlayerRecord => "playerRecord", Wording::Reference(Sentence::Record),
    PlayerRecording => "playerRecording", Wording::Own,
    PlayerChannel => "playerChannel", Wording::Own,
    PlayerChannelPrevious => "playerChannelPrevious", Wording::Own,
    PlayerChannelNext => "playerChannelNext", Wording::Own,
    FailureLiveTvNoService => "failureLiveTvNoService", Wording::Own,
    FailureLiveTvDenied => "failureLiveTvDenied", Wording::Own,
    FailureNoTuner => "failureNoTuner", Wording::Own,
    FailureTunerGone => "failureTunerGone", Wording::Own,
    FailureLiveStreamDropped => "failureLiveStreamDropped", Wording::Own,
    FailureTunerReleased => "failureTunerReleased", Wording::Own,
    FailureGuideOutOfRange => "failureGuideOutOfRange", Wording::Own,
    FailureLiveNotRelayable => "failureLiveNotRelayable", Wording::Own,
    NavDashboard => "navDashboard", Wording::Reference(Sentence::TabDashboard),
    PluginsTitle => "pluginsTitle", Wording::Reference(Sentence::TabPlugins),
    PluginsEnable => "pluginsEnable", Wording::Reference(Sentence::EnablePlugin),
    PluginsDisable => "pluginsDisable", Wording::Reference(Sentence::DisablePlugin),
    PluginsUninstall => "pluginsUninstall", Wording::Reference(Sentence::ButtonUninstall),
    PluginsConfigurationPages => "pluginsConfigurationPages", Wording::Own,
    ConfirmUninstallPlugin => "confirmUninstallPlugin", Wording::Own,
    ConfirmTypeName => "confirmTypeName", Wording::Own,
    ConfirmProceed => "confirmProceed", Wording::Own,
    ConfirmCancel => "confirmCancel", Wording::Reference(Sentence::ButtonCancel),
    FailureWrotePluginEnable => "failureWrotePluginEnable", Wording::Own,
    FailureWrotePluginDisable => "failureWrotePluginDisable", Wording::Own,
    FailureWrotePluginUninstall => "failureWrotePluginUninstall", Wording::Own,
    FailureWrotePluginConfiguration => "failureWrotePluginConfiguration", Wording::Own,
    DashboardHome => "dashboardHome", Wording::Reference(Sentence::Home),
    DashboardServer => "dashboardServer", Wording::Own,
    DashboardVersion => "dashboardVersion", Wording::Own,
    DashboardSessions => "dashboardSessions", Wording::Own,
    DashboardSessionNothing => "dashboardSessionNothing", Wording::Own,
    DashboardRunningTasks => "dashboardRunningTasks", Wording::Reference(Sentence::HeaderRunningTasks),
    DashboardScanning => "dashboardScanning", Wording::Own,
    DashboardScanAll => "dashboardScanAll", Wording::Reference(Sentence::ButtonScanAllLibraries),
    DashboardRestart => "dashboardRestart", Wording::Reference(Sentence::Restart),
    DashboardShutdown => "dashboardShutdown", Wording::Own,
    DashboardRestartRequired => "dashboardRestartRequired", Wording::Own,
    DashboardSettings => "dashboardSettings", Wording::Reference(Sentence::General),
    DashboardNetworking => "dashboardNetworking", Wording::Reference(Sentence::TabNetworking),
    DashboardBranding => "dashboardBranding", Wording::Reference(Sentence::HeaderBranding),
    DashboardResume => "dashboardResume", Wording::Own,
    DashboardStreaming => "dashboardStreaming", Wording::Reference(Sentence::TabStreaming),
    DashboardTranscoding => "dashboardTranscoding", Wording::Reference(Sentence::Transcoding),
    DashboardTrickplay => "dashboardTrickplay", Wording::Reference(Sentence::Trickplay),
    DashboardPaths => "dashboardPaths", Wording::Reference(Sentence::HeaderPaths),
    DashboardQuickConnect => "dashboardQuickConnect", Wording::Reference(Sentence::QuickConnect),
    DashboardPerformance => "dashboardPerformance", Wording::Reference(Sentence::HeaderPerformance),
    NetworkingAddresses => "networkingAddresses", Wording::Reference(Sentence::HeaderServerAddressSettings),
    NetworkingRemote => "networkingRemote", Wording::Reference(Sentence::HeaderRemoteAccessSettings),
    NetworkingProtocols => "networkingProtocols", Wording::Reference(Sentence::HeaderNetworking),
    NetworkingDiscovery => "networkingDiscovery", Wording::Reference(Sentence::HeaderAutoDiscovery),
    TranscodingHardwareEncoding => "transcodingHardwareEncoding", Wording::Reference(Sentence::LabelHardwareEncodingOptions),
    TranscodingEncodingFormat => "transcodingEncodingFormat", Wording::Reference(Sentence::LabelEncodingFormatOptions),
    GeneralServerName => "generalServerName", Wording::Reference(Sentence::LabelServerName),
    GeneralServerNameHelp => "generalServerNameHelp", Wording::Reference(Sentence::LabelServerNameHelp),
    GeneralDisplayLanguage => "generalDisplayLanguage", Wording::Reference(Sentence::LabelPreferredDisplayLanguage),
    GeneralDisplayLanguageHelp => "generalDisplayLanguageHelp", Wording::Reference(Sentence::LabelDisplayLanguageHelp),
    GeneralMetadataPath => "generalMetadataPath", Wording::Reference(Sentence::LabelMetadataPath),
    GeneralMetadataPathHelp => "generalMetadataPathHelp", Wording::Reference(Sentence::LabelMetadataPathHelp),
    GeneralQuickConnect => "generalQuickConnect", Wording::Reference(Sentence::EnableQuickConnect),
    GeneralScanConcurrency => "generalScanConcurrency", Wording::Reference(Sentence::LibraryScanFanoutConcurrency),
    GeneralScanConcurrencyHelp => "generalScanConcurrencyHelp", Wording::Reference(Sentence::LibraryScanFanoutConcurrencyHelp),
    NetworkingPort => "networkingPort", Wording::Reference(Sentence::LabelLocalHttpServerPortNumber),
    NetworkingPortHelp => "networkingPortHelp", Wording::Reference(Sentence::LabelLocalHttpServerPortNumberHelp),
    NetworkingBaseUrl => "networkingBaseUrl", Wording::Reference(Sentence::LabelBaseUrl),
    NetworkingBaseUrlHelp => "networkingBaseUrlHelp", Wording::Own,
    NetworkingLanNetworks => "networkingLanNetworks", Wording::Reference(Sentence::LabelLanNetworks),
    NetworkingLanNetworksHelp => "networkingLanNetworksHelp", Wording::Reference(Sentence::LanNetworksHelp),
    NetworkingKnownProxies => "networkingKnownProxies", Wording::Reference(Sentence::LabelKnownProxies),
    NetworkingKnownProxiesHelp => "networkingKnownProxiesHelp", Wording::Reference(Sentence::KnownProxiesHelp),
    NetworkingRemoteAccess => "networkingRemoteAccess", Wording::Reference(Sentence::AllowRemoteAccess),
    NetworkingRemoteAccessHelp => "networkingRemoteAccessHelp", Wording::Reference(Sentence::AllowRemoteAccessHelp),
    NetworkingRemoteFilter => "networkingRemoteFilter", Wording::Reference(Sentence::LabelAllowedRemoteAddresses),
    NetworkingRemoteFilterHelp => "networkingRemoteFilterHelp", Wording::Reference(Sentence::AllowedRemoteAddressesHelp),
    NetworkingPublicPort => "networkingPublicPort", Wording::Reference(Sentence::LabelPublicHttpPort),
    NetworkingPublicPortHelp => "networkingPublicPortHelp", Wording::Reference(Sentence::LabelPublicHttpPortHelp),
    NetworkingIpv4 => "networkingIpv4", Wording::Reference(Sentence::LabelEnableIP4),
    NetworkingIpv4Help => "networkingIpv4Help", Wording::Reference(Sentence::LabelEnableIP4Help),
    NetworkingIpv6 => "networkingIpv6", Wording::Reference(Sentence::LabelEnableIP6),
    NetworkingIpv6Help => "networkingIpv6Help", Wording::Reference(Sentence::LabelEnableIP6Help),
    NetworkingAutoDiscovery => "networkingAutoDiscovery", Wording::Reference(Sentence::LabelAutomaticDiscovery),
    NetworkingAutoDiscoveryHelp => "networkingAutoDiscoveryHelp", Wording::Reference(Sentence::LabelAutomaticDiscoveryHelp),
    BrandingSplashscreen => "brandingSplashscreen", Wording::Reference(Sentence::EnableSplashScreen),
    BrandingLoginDisclaimer => "brandingLoginDisclaimer", Wording::Reference(Sentence::LabelLoginDisclaimer),
    BrandingLoginDisclaimerHelp => "brandingLoginDisclaimerHelp", Wording::Reference(Sentence::LabelLoginDisclaimerHelp),
    BrandingCustomCss => "brandingCustomCss", Wording::Reference(Sentence::LabelCustomCss),
    BrandingCustomCssHelp => "brandingCustomCssHelp", Wording::Reference(Sentence::LabelCustomCssHelp),
    ResumeMinimumPercentage => "resumeMinimumPercentage", Wording::Reference(Sentence::LabelMinResumePercentage),
    ResumeMinimumPercentageHelp => "resumeMinimumPercentageHelp", Wording::Reference(Sentence::LabelMinAudiobookResumeHelp),
    ResumeMaximumPercentage => "resumeMaximumPercentage", Wording::Reference(Sentence::LabelMaxResumePercentage),
    ResumeMaximumPercentageHelp => "resumeMaximumPercentageHelp", Wording::Reference(Sentence::LabelMaxResumePercentageHelp),
    ResumeMinimumAudiobook => "resumeMinimumAudiobook", Wording::Reference(Sentence::LabelMinAudiobookResume),
    ResumeMinimumAudiobookHelp => "resumeMinimumAudiobookHelp", Wording::Reference(Sentence::LabelMinAudiobookResumeHelp),
    ResumeMaximumAudiobook => "resumeMaximumAudiobook", Wording::Reference(Sentence::LabelMaxAudiobookResume),
    ResumeMaximumAudiobookHelp => "resumeMaximumAudiobookHelp", Wording::Reference(Sentence::LabelMaxAudiobookResumeHelp),
    ResumeMinimumDuration => "resumeMinimumDuration", Wording::Reference(Sentence::LabelMinResumeDuration),
    ResumeMinimumDurationHelp => "resumeMinimumDurationHelp", Wording::Reference(Sentence::LabelMinResumeDurationHelp),
    StreamingBitrateLimit => "streamingBitrateLimit", Wording::Reference(Sentence::LabelRemoteClientBitrateLimit),
    StreamingBitrateLimitHelp => "streamingBitrateLimitHelp", Wording::Reference(Sentence::LabelRemoteClientBitrateLimitHelp),
    TranscodingHardwareAcceleration => "transcodingHardwareAcceleration", Wording::Reference(Sentence::LabelHardwareAccelerationType),
    TranscodingHardwareAccelerationHelp => "transcodingHardwareAccelerationHelp", Wording::Reference(Sentence::LabelHardwareAccelerationTypeHelp),
    TranscodingAccelerationNone => "transcodingAccelerationNone", Wording::Reference(Sentence::None),
    TranscodingAccelerationAmf => "transcodingAccelerationAmf", Wording::Own,
    TranscodingAccelerationNvenc => "transcodingAccelerationNvenc", Wording::Own,
    TranscodingAccelerationQsv => "transcodingAccelerationQsv", Wording::Own,
    TranscodingAccelerationVaapi => "transcodingAccelerationVaapi", Wording::Own,
    TranscodingAccelerationRkmpp => "transcodingAccelerationRkmpp", Wording::Own,
    TranscodingAccelerationVideoToolbox => "transcodingAccelerationVideoToolbox", Wording::Own,
    TranscodingAccelerationV4l2m2m => "transcodingAccelerationV4l2m2m", Wording::Own,
    TranscodingEnableHardwareEncoding => "transcodingEnableHardwareEncoding", Wording::Reference(Sentence::EnableHardwareEncoding),
    TranscodingEncodingFormatHelp => "transcodingEncodingFormatHelp", Wording::Reference(Sentence::EncodingFormatHelp),
    TranscodingAllowHevc => "transcodingAllowHevc", Wording::Reference(Sentence::AllowHevcEncoding),
    TranscodingTonemapping => "transcodingTonemapping", Wording::Reference(Sentence::EnableTonemapping),
    TranscodingTonemappingHelp => "transcodingTonemappingHelp", Wording::Reference(Sentence::AllowTonemappingHelp),
    TranscodingThreadCount => "transcodingThreadCount", Wording::Reference(Sentence::LabelTranscodingThreadCount),
    TranscodingThreadCountHelp => "transcodingThreadCountHelp", Wording::Reference(Sentence::LabelTranscodingThreadCountHelp),
    TranscodingPath => "transcodingPath", Wording::Reference(Sentence::LabelTranscodePath),
    TranscodingPathHelp => "transcodingPathHelp", Wording::Reference(Sentence::LabelTranscodingTempPathHelp),
    TranscodingDownMixBoost => "transcodingDownMixBoost", Wording::Reference(Sentence::LabelDownMixAudioScale),
    TranscodingDownMixBoostHelp => "transcodingDownMixBoostHelp", Wording::Reference(Sentence::LabelDownMixAudioScaleHelp),
    TranscodingThrottle => "transcodingThrottle", Wording::Reference(Sentence::AllowFfmpegThrottling),
    TranscodingThrottleHelp => "transcodingThrottleHelp", Wording::Reference(Sentence::AllowFfmpegThrottlingHelp),
    TranscodingThrottleDelay => "transcodingThrottleDelay", Wording::Reference(Sentence::LabelThrottleDelaySeconds),
    TranscodingThrottleDelayHelp => "transcodingThrottleDelayHelp", Wording::Reference(Sentence::LabelThrottleDelaySecondsHelp),
    TrickplayHardwareDecoding => "trickplayHardwareDecoding", Wording::Reference(Sentence::LabelTrickplayAccel),
    TrickplayHardwareEncoding => "trickplayHardwareEncoding", Wording::Reference(Sentence::LabelTrickplayAccelEncoding),
    TrickplayHardwareEncodingHelp => "trickplayHardwareEncodingHelp", Wording::Reference(Sentence::LabelTrickplayAccelEncodingHelp),
    TrickplayInterval => "trickplayInterval", Wording::Reference(Sentence::LabelImageInterval),
    TrickplayIntervalHelp => "trickplayIntervalHelp", Wording::Reference(Sentence::LabelImageIntervalHelp),
    TrickplayTileWidth => "trickplayTileWidth", Wording::Reference(Sentence::LabelTileWidth),
    TrickplayTileWidthHelp => "trickplayTileWidthHelp", Wording::Reference(Sentence::LabelTileWidthHelp),
    TrickplayTileHeight => "trickplayTileHeight", Wording::Reference(Sentence::LabelTileHeight),
    TrickplayTileHeightHelp => "trickplayTileHeightHelp", Wording::Reference(Sentence::LabelTileHeightHelp),
    TrickplayJpegQuality => "trickplayJpegQuality", Wording::Reference(Sentence::LabelJpegQuality),
    TrickplayJpegQualityHelp => "trickplayJpegQualityHelp", Wording::Reference(Sentence::LabelJpegQualityHelp),
    TrickplayQscale => "trickplayQscale", Wording::Reference(Sentence::LabelQscale),
    TrickplayQscaleHelp => "trickplayQscaleHelp", Wording::Reference(Sentence::LabelQscaleHelp),
    TrickplayThreads => "trickplayThreads", Wording::Reference(Sentence::LabelTrickplayThreads),
    TrickplayThreadsHelp => "trickplayThreadsHelp", Wording::Reference(Sentence::LabelTrickplayThreadsHelp),
    DashboardSave => "dashboardSave", Wording::Reference(Sentence::Save),
    DashboardSaved => "dashboardSaved", Wording::Own,
    DashboardUnsaved => "dashboardUnsaved", Wording::Own,
    DashboardLeaveAnyway => "dashboardLeaveAnyway", Wording::Own,
    DashboardStayHere => "dashboardStayHere", Wording::Own,
    NavSettings => "navSettings", Wording::Reference(Sentence::Settings),
    SettingsTitle => "settingsTitle", Wording::Reference(Sentence::Settings),
    SettingsProfile => "settingsProfile", Wording::Reference(Sentence::Profile),
    SettingsDisplay => "settingsDisplay", Wording::Reference(Sentence::Display),
    SettingsHome => "settingsHome", Wording::Own,
    SettingsPlayback => "settingsPlayback", Wording::Reference(Sentence::TitlePlayback),
    SettingsSubtitles => "settingsSubtitles", Wording::Reference(Sentence::Subtitles),
    SettingsControls => "settingsControls", Wording::Own,
    SettingsQuickConnect => "settingsQuickConnect", Wording::Reference(Sentence::QuickConnect),
    SettingsSave => "settingsSave", Wording::Reference(Sentence::Save),
    SettingsServerChanged => "settingsServerChanged", Wording::Own,
    ProfileAdministrator => "profileAdministrator", Wording::Own,
    ProfileMember => "profileMember", Wording::Own,
    ProfileLastActive => "profileLastActive", Wording::Own,
    ProfileDisplayName => "profileDisplayName", Wording::Reference(Sentence::LabelDisplayName),
    ProfileSaveName => "profileSaveName", Wording::Own,
    ProfileImage => "profileImage", Wording::Own,
    ProfileImageChoose => "profileImageChoose", Wording::Own,
    PasswordCurrent => "passwordCurrent", Wording::Reference(Sentence::LabelCurrentPassword),
    PasswordNew => "passwordNew", Wording::Reference(Sentence::LabelNewPassword),
    PasswordChange => "passwordChange", Wording::Own,
    PasswordOtherDevices => "passwordOtherDevices", Wording::Own,
    DisplayMissingEpisodes => "displayMissingEpisodes", Wording::Own,
    DisplayMissingEpisodesHelp => "displayMissingEpisodesHelp", Wording::Own,
    HomeOrder => "homeOrder", Wording::Reference(Sentence::HeaderLibraries),
    MoveUp => "moveUp", Wording::Reference(Sentence::Up),
    MoveDown => "moveDown", Wording::Reference(Sentence::Down),
    HomeInMyMedia => "homeInMyMedia", Wording::Own,
    HomeContinueWatchingRow => "homeContinueWatchingRow", Wording::Own,
    HomeNextUpRow => "homeNextUpRow", Wording::Own,
    PlaybackAudioLanguage => "playbackAudioLanguage", Wording::Reference(Sentence::LabelAudioLanguagePreference),
    PlaybackSubtitleLanguage => "playbackSubtitleLanguage", Wording::Reference(Sentence::LabelPreferredSubtitleLanguage),
    PlaybackLanguageAny => "playbackLanguageAny", Wording::Reference(Sentence::AnyLanguage),
    PlaybackDefaultAudioTrack => "playbackDefaultAudioTrack", Wording::Own,
    PlaybackSubtitleMode => "playbackSubtitleMode", Wording::Reference(Sentence::LabelSubtitlePlaybackMode),
    PlaybackSubtitleModeDefault => "playbackSubtitleModeDefault", Wording::Reference(Sentence::Default),
    PlaybackSubtitleModeDefaultHelp => "playbackSubtitleModeDefaultHelp", Wording::Own,
    PlaybackSubtitleModeAlways => "playbackSubtitleModeAlways", Wording::Own,
    PlaybackSubtitleModeAlwaysHelp => "playbackSubtitleModeAlwaysHelp", Wording::Own,
    PlaybackSubtitleModeOnlyForced => "playbackSubtitleModeOnlyForced", Wording::Reference(Sentence::OnlyForcedSubtitles),
    PlaybackSubtitleModeOnlyForcedHelp => "playbackSubtitleModeOnlyForcedHelp", Wording::Own,
    PlaybackSubtitleModeNone => "playbackSubtitleModeNone", Wording::Reference(Sentence::None),
    PlaybackSubtitleModeNoneHelp => "playbackSubtitleModeNoneHelp", Wording::Own,
    PlaybackSubtitleModeSmart => "playbackSubtitleModeSmart", Wording::Reference(Sentence::Smart),
    PlaybackSubtitleModeSmartHelp => "playbackSubtitleModeSmartHelp", Wording::Own,
    PlaybackNextEpisode => "playbackNextEpisode", Wording::Own,
    PlaybackQuality => "playbackQuality", Wording::Own,
    PlaybackSkipBack => "playbackSkipBack", Wording::Own,
    PlaybackSkipForward => "playbackSkipForward", Wording::Own,
    PlaybackSeconds => "playbackSeconds", Wording::Reference(Sentence::ValueSeconds),
    PlaybackSyncPlay => "playbackSyncPlay", Wording::Reference(Sentence::ButtonSyncPlay),
    PlaybackSyncOffset => "playbackSyncOffset", Wording::Reference(Sentence::LabelSyncPlaySettingsExtraTimeOffset),
    PlaybackSyncMilliseconds => "playbackSyncMilliseconds", Wording::Own,
    PlaybackSyncMethod => "playbackSyncMethod", Wording::Reference(Sentence::LabelSyncPlaySyncMethod),
    PlaybackSyncMethodAuto => "playbackSyncMethodAuto", Wording::Own,
    PlaybackSyncMethodRate => "playbackSyncMethodRate", Wording::Own,
    PlaybackSyncMethodSeek => "playbackSyncMethodSeek", Wording::Own,
    PlaybackSyncRateAttempts => "playbackSyncRateAttempts", Wording::Own,
    PlaybackSyncSeekAttempts => "playbackSyncSeekAttempts", Wording::Own,
    SubtitlesSize => "subtitlesSize", Wording::Reference(Sentence::LabelTextSize),
    SubtitlesColour => "subtitlesColour", Wording::Own,
    SubtitlesBackground => "subtitlesBackground", Wording::Own,
    SubtitlesOpacity => "subtitlesOpacity", Wording::Own,
    SubtitlesShadow => "subtitlesShadow", Wording::Reference(Sentence::LabelDropShadow),
    SubtitlesBurnedIn => "subtitlesBurnedIn", Wording::Own,
    SubtitleSizeSmall => "subtitleSizeSmall", Wording::Reference(Sentence::Small),
    SubtitleSizeMedium => "subtitleSizeMedium", Wording::Own,
    SubtitleSizeLarge => "subtitleSizeLarge", Wording::Reference(Sentence::Large),
    SubtitleSizeHuge => "subtitleSizeHuge", Wording::Reference(Sentence::ExtraLarge),
    ColourWhite => "colourWhite", Wording::Reference(Sentence::SubtitleWhite),
    ColourBlack => "colourBlack", Wording::Reference(Sentence::SubtitleBlack),
    ColourRed => "colourRed", Wording::Reference(Sentence::SubtitleRed),
    ColourGreen => "colourGreen", Wording::Reference(Sentence::SubtitleGreen),
    ColourBlue => "colourBlue", Wording::Reference(Sentence::SubtitleBlue),
    ColourYellow => "colourYellow", Wording::Reference(Sentence::SubtitleYellow),
    ColourMagenta => "colourMagenta", Wording::Reference(Sentence::SubtitleMagenta),
    ColourCyan => "colourCyan", Wording::Reference(Sentence::SubtitleCyan),
    ShadowNone => "shadowNone", Wording::Reference(Sentence::None),
    ShadowDrop => "shadowDrop", Wording::Reference(Sentence::LabelDropShadow),
    ShadowOutline => "shadowOutline", Wording::Own,
    KeySpace => "keySpace", Wording::Reference(Sentence::ButtonSpace),
    KeyK => "keyK", Wording::Own,
    KeyF => "keyF", Wording::Own,
    KeyM => "keyM", Wording::Own,
    KeyN => "keyN", Wording::Own,
    KeyP => "keyP", Wording::Own,
    KeyEscape => "keyEscape", Wording::Own,
    KeyArrowLeft => "keyArrowLeft", Wording::Own,
    KeyArrowRight => "keyArrowRight", Wording::Own,
    KeyArrowUp => "keyArrowUp", Wording::Own,
    KeyArrowDown => "keyArrowDown", Wording::Own,
    DoesTogglePlay => "doesTogglePlay", Wording::Own,
    DoesSkipBack => "doesSkipBack", Wording::Own,
    DoesSkipForward => "doesSkipForward", Wording::Own,
    DoesVolumeUp => "doesVolumeUp", Wording::Own,
    DoesVolumeDown => "doesVolumeDown", Wording::Own,
    DoesToggleMute => "doesToggleMute", Wording::Own,
    DoesFullscreen => "doesFullscreen", Wording::Own,
    DoesNext => "doesNext", Wording::Own,
    DoesPrevious => "doesPrevious", Wording::Own,
    DoesLeave => "doesLeave", Wording::Own,
    QuickConnectDescription => "quickConnectDescription", Wording::Own,
    QuickConnectCode => "quickConnectCode", Wording::Reference(Sentence::LabelQuickConnectCode),
    QuickConnectAuthorize => "quickConnectAuthorize", Wording::Reference(Sentence::Authorize),
    QuickConnectAuthorized => "quickConnectAuthorized", Wording::Own,
    ConfirmAuthorizeQuickConnect => "confirmAuthorizeQuickConnect", Wording::Own,
    FailureQuickConnectUnknown => "failureQuickConnectUnknown", Wording::Own,
    FailureQuickConnectExpired => "failureQuickConnectExpired", Wording::Own,
    FailureQuickConnectUsed => "failureQuickConnectUsed", Wording::Own,
    FailureQuickConnectDisabled => "failureQuickConnectDisabled", Wording::Own,
    FailureQuickConnectShape => "failureQuickConnectShape", Wording::Own,
    FailureImageType => "failureImageType", Wording::Own,
    FailureImageTooLarge => "failureImageTooLarge", Wording::Own,
    FailureWroteUserName => "failureWroteUserName", Wording::Own,
    FailureWroteUserConfiguration => "failureWroteUserConfiguration", Wording::Own,
    FailureWrotePreferences => "failureWrotePreferences", Wording::Own,
    FailureWroteQuickConnect => "failureWroteQuickConnect", Wording::Own,
    ConfirmRestart => "confirmRestart", Wording::Own,
    ConfirmShutdown => "confirmShutdown", Wording::Own,
    FailureWroteConfiguration => "failureWroteConfiguration", Wording::Own,
    FailureWroteScan => "failureWroteScan", Wording::Own,
    FailureWroteRestart => "failureWroteRestart", Wording::Own,
    FailureWroteShutdown => "failureWroteShutdown", Wording::Own,
    UsersTitle => "usersTitle", Wording::Reference(Sentence::HeaderUsers),
    UsersAdd => "usersAdd", Wording::Reference(Sentence::ButtonAddUser),
    UsersDelete => "usersDelete", Wording::Reference(Sentence::Delete),
    UsersName => "usersName", Wording::Reference(Sentence::Name),
    UsersPassword => "usersPassword", Wording::Reference(Sentence::LabelPassword),
    UsersProfile => "usersProfile", Wording::Reference(Sentence::Profile),
    UsersAccess => "usersAccess", Wording::Reference(Sentence::TabAccess),
    UsersParental => "usersParental", Wording::Reference(Sentence::ButtonParentalControl),
    UsersImageUpload => "usersImageUpload", Wording::Own,
    UsersImageRemove => "usersImageRemove", Wording::Own,
    UsersLastSeen => "usersLastSeen", Wording::Own,
    UsersOwnAdministrator => "usersOwnAdministrator", Wording::Own,
    UsersRemoteAccess => "usersRemoteAccess", Wording::Reference(Sentence::AllowRemoteAccess),
    UsersRemoteAccessHelp => "usersRemoteAccessHelp", Wording::Reference(Sentence::AllowRemoteAccessHelp),
    UsersAdministrator => "usersAdministrator", Wording::Reference(Sentence::OptionAllowUserToManageServer),
    UsersFeatureAccess => "usersFeatureAccess", Wording::Reference(Sentence::HeaderFeatureAccess),
    UsersLiveTvAccess => "usersLiveTvAccess", Wording::Reference(Sentence::OptionAllowBrowsingLiveTv),
    UsersLiveTvManagement => "usersLiveTvManagement", Wording::Reference(Sentence::OptionAllowManageLiveTv),
    UsersPlayback => "usersPlayback", Wording::Reference(Sentence::HeaderPlayback),
    UsersMediaPlayback => "usersMediaPlayback", Wording::Reference(Sentence::OptionAllowMediaPlayback),
    UsersAudioTranscoding => "usersAudioTranscoding", Wording::Reference(Sentence::OptionAllowAudioPlaybackTranscoding),
    UsersVideoTranscoding => "usersVideoTranscoding", Wording::Reference(Sentence::OptionAllowVideoPlaybackTranscoding),
    UsersRemuxing => "usersRemuxing", Wording::Reference(Sentence::OptionAllowVideoPlaybackRemuxing),
    UsersPlaybackHelp => "usersPlaybackHelp", Wording::Reference(Sentence::OptionAllowMediaPlaybackTranscodingHelp),
    UsersBitrateLimit => "usersBitrateLimit", Wording::Reference(Sentence::LabelRemoteClientBitrateLimit),
    UsersBitrateLimitHelp => "usersBitrateLimitHelp", Wording::Reference(Sentence::LabelRemoteClientBitrateLimitHelp),
    UsersBitrateLimitOverride => "usersBitrateLimitOverride", Wording::Reference(Sentence::LabelUserRemoteClientBitrateLimitHelp),
    UsersSyncPlay => "usersSyncPlay", Wording::Reference(Sentence::LabelSyncPlayAccess),
    UsersSyncPlayHelp => "usersSyncPlayHelp", Wording::Reference(Sentence::SyncPlayAccessHelp),
    UsersSyncPlayCreate => "usersSyncPlayCreate", Wording::Reference(Sentence::LabelSyncPlayAccessCreateAndJoinGroups),
    UsersSyncPlayJoin => "usersSyncPlayJoin", Wording::Reference(Sentence::LabelSyncPlayAccessJoinGroups),
    UsersSyncPlayNone => "usersSyncPlayNone", Wording::Reference(Sentence::LabelSyncPlayAccessNone),
    UsersDeletion => "usersDeletion", Wording::Reference(Sentence::HeaderAllowMediaDeletionFrom),
    UsersDeletionAll => "usersDeletionAll", Wording::Reference(Sentence::AllLibraries),
    UsersOther => "usersOther", Wording::Reference(Sentence::Other),
    UsersDownloads => "usersDownloads", Wording::Reference(Sentence::OptionAllowContentDownload),
    UsersDownloadsHelp => "usersDownloadsHelp", Wording::Reference(Sentence::OptionAllowContentDownloadHelp),
    UsersDisabled => "usersDisabled", Wording::Reference(Sentence::OptionDisableUser),
    UsersDisabledHelp => "usersDisabledHelp", Wording::Reference(Sentence::OptionDisableUserHelp),
    UsersHidden => "usersHidden", Wording::Reference(Sentence::OptionHideUser),
    UsersHiddenHelp => "usersHiddenHelp", Wording::Reference(Sentence::OptionHideUserFromLoginHelp),
    UsersLockout => "usersLockout", Wording::Reference(Sentence::LabelUserLoginAttemptsBeforeLockout),
    UsersLockoutHelp => "usersLockoutHelp", Wording::Reference(Sentence::OptionLoginAttemptsBeforeLockout),
    UsersLockoutZero => "usersLockoutZero", Wording::Reference(Sentence::OptionLoginAttemptsBeforeLockoutHelp),
    UsersSessions => "usersSessions", Wording::Reference(Sentence::LabelUserMaxActiveSessions),
    UsersSessionsHelp => "usersSessionsHelp", Wording::Reference(Sentence::OptionMaxActiveSessions),
    UsersSessionsZero => "usersSessionsZero", Wording::Reference(Sentence::OptionMaxActiveSessionsHelp),
    UsersLibraryAccess => "usersLibraryAccess", Wording::Reference(Sentence::ButtonLibraryAccess),
    UsersAllLibraries => "usersAllLibraries", Wording::Reference(Sentence::OptionEnableAccessToAllLibraries),
    UsersLibraries => "usersLibraries", Wording::Reference(Sentence::HeaderLibraries),
    UsersLibrariesHelp => "usersLibrariesHelp", Wording::Reference(Sentence::LibraryAccessHelp),
    UsersChannelAccess => "usersChannelAccess", Wording::Reference(Sentence::HeaderChannelAccess),
    UsersAllChannels => "usersAllChannels", Wording::Reference(Sentence::OptionEnableAccessToAllChannels),
    UsersChannels => "usersChannels", Wording::Reference(Sentence::Channels),
    UsersChannelsHelp => "usersChannelsHelp", Wording::Reference(Sentence::ChannelAccessHelp),
    UsersDeviceAccess => "usersDeviceAccess", Wording::Reference(Sentence::HeaderDeviceAccess),
    UsersAllDevices => "usersAllDevices", Wording::Reference(Sentence::OptionEnableAccessFromAllDevices),
    UsersDevices => "usersDevices", Wording::Reference(Sentence::HeaderDevices),
    UsersDevicesHelp => "usersDevicesHelp", Wording::Reference(Sentence::DeviceAccessHelp),
    UsersMaxRating => "usersMaxRating", Wording::Reference(Sentence::LabelMaxParentalRating),
    UsersMaxRatingHelp => "usersMaxRatingHelp", Wording::Reference(Sentence::MaxParentalRatingHelp),
    UsersAllowedTags => "usersAllowedTags", Wording::Reference(Sentence::LabelAllowContentWithTags),
    UsersAllowedTagsHelp => "usersAllowedTagsHelp", Wording::Reference(Sentence::AllowContentWithTagsHelp),
    UsersBlockedTags => "usersBlockedTags", Wording::Reference(Sentence::LabelBlockContentWithTags),
    UsersBlockedTagsHelp => "usersBlockedTagsHelp", Wording::Reference(Sentence::BlockContentWithTagsHelp),
    LibrariesTitle => "librariesTitle", Wording::Reference(Sentence::HeaderLibraries),
    LibrariesCreate => "librariesCreate", Wording::Own,
    LibrariesRename => "librariesRename", Wording::Reference(Sentence::ButtonRename),
    LibrariesRemove => "librariesRemove", Wording::Reference(Sentence::ButtonRemove),
    LibrariesFolders => "librariesFolders", Wording::Reference(Sentence::Folders),
    LibrariesPathAdd => "librariesPathAdd", Wording::Own,
    LibrariesPathRemove => "librariesPathRemove", Wording::Reference(Sentence::ButtonRemove),
    LibrariesBrowse => "librariesBrowse", Wording::Own,
    LibrariesManage => "librariesManage", Wording::Reference(Sentence::ManageLibrary),
    LibrariesScan => "librariesScan", Wording::Reference(Sentence::ScanLibrary),
    LibrariesScanning => "librariesScanning", Wording::Own,
    LibrariesSettings => "librariesSettings", Wording::Reference(Sentence::HeaderLibrarySettings),
    LibrariesMetadataLanguage => "librariesMetadataLanguage", Wording::Reference(Sentence::LabelMetadataDownloadLanguage),
    LibrariesMetadataCountry => "librariesMetadataCountry", Wording::Reference(Sentence::LabelCountry),
    LibrariesPhotos => "librariesPhotos", Wording::Reference(Sentence::EnablePhotos),
    LibrariesPhotosHelp => "librariesPhotosHelp", Wording::Reference(Sentence::EnablePhotosHelp),
    LibrariesRealtimeMonitor => "librariesRealtimeMonitor", Wording::Reference(Sentence::LabelEnableRealtimeMonitor),
    LibrariesRealtimeMonitorHelp => "librariesRealtimeMonitorHelp", Wording::Reference(Sentence::LabelEnableRealtimeMonitorHelp),
    LibrariesMetadataReaders => "librariesMetadataReaders", Wording::Reference(Sentence::LabelMetadataReaders),
    LibrariesMetadataReadersHelp => "librariesMetadataReadersHelp", Wording::Reference(Sentence::LabelMetadataReadersHelp),
    LibrariesSaveArtwork => "librariesSaveArtwork", Wording::Reference(Sentence::LabelSaveLocalMetadata),
    LibrariesSaveArtworkHelp => "librariesSaveArtworkHelp", Wording::Reference(Sentence::LabelSaveLocalMetadataHelp),
    LibrariesChapterImages => "librariesChapterImages", Wording::Reference(Sentence::HeaderDummyChapter),
    LibrariesChapterExtraction => "librariesChapterExtraction", Wording::Reference(Sentence::OptionExtractChapterImage),
    LibrariesChapterExtractionHelp => "librariesChapterExtractionHelp", Wording::Reference(Sentence::ExtractChapterImagesHelp),
    LibrariesSubtitleDownloads => "librariesSubtitleDownloads", Wording::Reference(Sentence::HeaderSubtitleDownloads),
    LibrariesDownloadLanguages => "librariesDownloadLanguages", Wording::Reference(Sentence::LabelDownloadLanguages),
    LibrariesSubtitleDownloaders => "librariesSubtitleDownloaders", Wording::Reference(Sentence::LabelSubtitleDownloaders),
    LibrariesSubtitleDownloadersHelp => "librariesSubtitleDownloadersHelp", Wording::Reference(Sentence::SubtitleDownloadersHelp),
    LibrariesSaveSubtitles => "librariesSaveSubtitles", Wording::Reference(Sentence::SaveSubtitlesIntoMediaFolders),
    LibrariesSaveSubtitlesHelp => "librariesSaveSubtitlesHelp", Wording::Reference(Sentence::SaveSubtitlesIntoMediaFoldersHelp),
    ConfirmDeleteUser => "confirmDeleteUser", Wording::Own,
    ConfirmDeleteLibrary => "confirmDeleteLibrary", Wording::Own,
    ConfirmDeletePath => "confirmDeletePath", Wording::Own,
    ConfirmRemoveUserImage => "confirmRemoveUserImage", Wording::Own,
    FailureWroteCollectionCreate => "failureWroteCollectionCreate", Wording::Own,
    FailureWrotePlaylistCreate => "failureWrotePlaylistCreate", Wording::Own,
    FailureWrotePlaylistRename => "failureWrotePlaylistRename", Wording::Own,
    FailureWrotePlaylistDelete => "failureWrotePlaylistDelete", Wording::Own,
    FailureWrotePlaylistRemove => "failureWrotePlaylistRemove", Wording::Own,
    FailureWrotePlaylistMove => "failureWrotePlaylistMove", Wording::Own,
    FailureWrotePlaylistShare => "failureWrotePlaylistShare", Wording::Own,
    FailureWroteCollectionAdd => "failureWroteCollectionAdd", Wording::Own,
    FailureWroteCollectionRemove => "failureWroteCollectionRemove", Wording::Own,
    FailureWrotePlaylistAdd => "failureWrotePlaylistAdd", Wording::Own,
    OverflowMarkPlayed => "overflowMarkPlayed", Wording::Reference(Sentence::MarkPlayed),
    OverflowMarkUnplayed => "overflowMarkUnplayed", Wording::Reference(Sentence::MarkUnplayed),
    OverflowFavorite => "overflowFavorite", Wording::Reference(Sentence::AddToFavorites),
    OverflowUnfavorite => "overflowUnfavorite", Wording::Own,
    OverflowAddToCollection => "overflowAddToCollection", Wording::Reference(Sentence::AddToCollection),
    OverflowAddToPlaylist => "overflowAddToPlaylist", Wording::Reference(Sentence::AddToPlaylist),
    OverflowRemoveFromCollection => "overflowRemoveFromCollection", Wording::Own,
    OverflowCreateAndFile => "overflowCreateAndFile", Wording::Own,
    OverflowOpen => "overflowOpen", Wording::Reference(Sentence::ButtonMore),
    MenuPlay => "menuPlay", Wording::Reference(Sentence::Play),
    MenuDeleteMedia => "menuDeleteMedia", Wording::Reference(Sentence::DeleteMedia),
    MenuCancelRecording => "menuCancelRecording", Wording::Reference(Sentence::CancelRecording),
    MenuCancelSeries => "menuCancelSeries", Wording::Reference(Sentence::CancelSeries),
    ConfirmCancelRecording => "confirmCancelRecording", Wording::Own,
    ConfirmCancelSeries => "confirmCancelSeries", Wording::Own,
    SheetCancel => "sheetCancel", Wording::Reference(Sentence::ButtonCancel),
    SheetPlayOn => "sheetPlayOn", Wording::Reference(Sentence::HeaderPlayOn),
    SheetSelectGroup => "sheetSelectGroup", Wording::Reference(Sentence::HeaderSyncPlaySelectGroup),
    SheetNewGroup => "sheetNewGroup", Wording::Reference(Sentence::LabelSyncPlayNewGroup),
    SheetNewGroupHelp => "sheetNewGroupHelp", Wording::Reference(Sentence::LabelSyncPlayNewGroupDescription),
    SheetHaltPlayback => "sheetHaltPlayback", Wording::Reference(Sentence::LabelSyncPlayHaltPlayback),
    SheetHaltPlaybackHelp => "sheetHaltPlaybackHelp", Wording::Reference(Sentence::LabelSyncPlayHaltPlaybackDescription),
    SheetLeaveGroup => "sheetLeaveGroup", Wording::Reference(Sentence::LabelSyncPlayLeaveGroup),
    SheetLeaveGroupHelp => "sheetLeaveGroupHelp", Wording::Reference(Sentence::LabelSyncPlayLeaveGroupDescription),
    CardPlay => "cardPlay", Wording::Reference(Sentence::Play),
    CardMarkPlayed => "cardMarkPlayed", Wording::Reference(Sentence::MarkPlayed),
    CardWatched => "cardWatched", Wording::Reference(Sentence::Watched),
    CardAddToFavorites => "cardAddToFavorites", Wording::Reference(Sentence::AddToFavorites),
    CardFavorite => "cardFavorite", Wording::Reference(Sentence::Favorite),
    FailureWroteUserCreate => "failureWroteUserCreate", Wording::Own,
    FailureWroteUserSave => "failureWroteUserSave", Wording::Own,
    FailureWroteUserDelete => "failureWroteUserDelete", Wording::Own,
    FailureWroteUserPassword => "failureWroteUserPassword", Wording::Own,
    FailureWroteUserImage => "failureWroteUserImage", Wording::Own,
    FailureWroteLibraryCreate => "failureWroteLibraryCreate", Wording::Own,
    FailureWroteLibraryRename => "failureWroteLibraryRename", Wording::Own,
    FailureWroteLibraryDelete => "failureWroteLibraryDelete", Wording::Own,
    FailureWroteLibraryPath => "failureWroteLibraryPath", Wording::Own,
    FailureWroteLibraryOptions => "failureWroteLibraryOptions", Wording::Own,
    Percent => "percent", Wording::Own,
    TasksTitle => "tasksTitle", Wording::Reference(Sentence::TabScheduledTasks),
    TasksLastRun => "tasksLastRun", Wording::Own,
    TasksLastRan => "tasksLastRan", Wording::Reference(Sentence::LabelScheduledTaskLastRan),
    TasksStopping => "tasksStopping", Wording::Reference(Sentence::LabelStopping),
    TasksFailed => "tasksFailed", Wording::Reference(Sentence::LabelFailed),
    TasksCancelled => "tasksCancelled", Wording::Reference(Sentence::LabelCancelled),
    TasksAborted => "tasksAborted", Wording::Reference(Sentence::LabelAbortedByServerShutdown),
    TasksDuration => "tasksDuration", Wording::Own,
    TasksTriggers => "tasksTriggers", Wording::Own,
    TasksTriggerDaily => "tasksTriggerDaily", Wording::Own,
    TasksTriggerInterval => "tasksTriggerInterval", Wording::Own,
    TasksTriggerStartup => "tasksTriggerStartup", Wording::Own,
    TasksTriggerRemove => "tasksTriggerRemove", Wording::Reference(Sentence::ButtonRemove),
    DistanceLessThanMinute => "distanceLessThanMinute", Wording::Own,
    DistanceLessThanMinutes => "distanceLessThanMinutes", Wording::Own,
    DistanceMinute => "distanceMinute", Wording::Own,
    DistanceMinutes => "distanceMinutes", Wording::Own,
    DistanceAboutHour => "distanceAboutHour", Wording::Own,
    DistanceAboutHours => "distanceAboutHours", Wording::Own,
    DistanceDay => "distanceDay", Wording::Own,
    DistanceDays => "distanceDays", Wording::Own,
    DistanceAboutMonth => "distanceAboutMonth", Wording::Own,
    DistanceAboutMonths => "distanceAboutMonths", Wording::Own,
    DistanceMonth => "distanceMonth", Wording::Own,
    DistanceMonths => "distanceMonths", Wording::Own,
    DistanceAboutYear => "distanceAboutYear", Wording::Own,
    DistanceAboutYears => "distanceAboutYears", Wording::Own,
    DistanceOverYear => "distanceOverYear", Wording::Own,
    DistanceOverYears => "distanceOverYears", Wording::Own,
    DistanceAlmostYear => "distanceAlmostYear", Wording::Own,
    DistanceAlmostYears => "distanceAlmostYears", Wording::Own,
    DistancePassed => "distancePassed", Wording::Own,
    DistanceAhead => "distanceAhead", Wording::Own,
    LogsTitle => "logsTitle", Wording::Reference(Sentence::TabLogs),
    LogsTail => "logsTail", Wording::Own,
    LogsSlowResponse => "logsSlowResponse", Wording::Reference(Sentence::LabelSlowResponseEnabled),
    LogsSlowResponseTime => "logsSlowResponseTime", Wording::Reference(Sentence::LabelSlowResponseTime),
    LogsMebibytes => "logsMebibytes", Wording::Own,
    ActivityTitle => "activityTitle", Wording::Reference(Sentence::HeaderActivity),
    ActivityWithUser => "activityWithUser", Wording::Own,
    ActivityWithoutUser => "activityWithoutUser", Wording::Own,
    ActivityAll => "activityAll", Wording::Reference(Sentence::All),
    ConfirmStopTask => "confirmStopTask", Wording::Own,
    FailureWroteTaskStart => "failureWroteTaskStart", Wording::Own,
    FailureWroteTaskStop => "failureWroteTaskStop", Wording::Own,
    FailureWroteTaskTriggers => "failureWroteTaskTriggers", Wording::Own,
    FailureLogMissing => "failureLogMissing", Wording::Own,
    CatalogTitle => "catalogTitle", Wording::Own,
    CatalogInstall => "catalogInstall", Wording::Reference(Sentence::HeaderInstall),
    CatalogInstalling => "catalogInstalling", Wording::Own,
    CatalogCancel => "catalogCancel", Wording::Reference(Sentence::ButtonCancel),
    CatalogVersions => "catalogVersions", Wording::Own,
    RepositoriesTitle => "repositoriesTitle", Wording::Reference(Sentence::TabRepositories),
    RepositoriesAdd => "repositoriesAdd", Wording::Reference(Sentence::Add),
    RepositoriesRemove => "repositoriesRemove", Wording::Reference(Sentence::ButtonRemove),
    RepositoriesUrl => "repositoriesUrl", Wording::Own,
    RepositoriesEmpty => "repositoriesEmpty", Wording::Reference(Sentence::MessageNoRepositories),
    RepositoriesEmptyHelp => "repositoriesEmptyHelp", Wording::Own,
    DevicesTitle => "devicesTitle", Wording::Reference(Sentence::HeaderDevices),
    DevicesRename => "devicesRename", Wording::Reference(Sentence::ButtonRename),
    KeysTitle => "keysTitle", Wording::Reference(Sentence::HeaderApiKeys),
    KeysHelp => "keysHelp", Wording::Own,
    ColumnApp => "columnApp", Wording::Reference(Sentence::LabelAppName),
    ColumnDevice => "columnDevice", Wording::Reference(Sentence::LabelDevice),
    ColumnIssued => "columnIssued", Wording::Reference(Sentence::HeaderDateIssued),
    ColumnKey => "columnKey", Wording::Reference(Sentence::HeaderApiKey),
    ColumnLastActive => "columnLastActive", Wording::Reference(Sentence::LastActive),
    ColumnLevel => "columnLevel", Wording::Reference(Sentence::LabelLevel),
    ColumnName => "columnName", Wording::Reference(Sentence::Name),
    ColumnOverview => "columnOverview", Wording::Reference(Sentence::Overview),
    ColumnTime => "columnTime", Wording::Reference(Sentence::LabelTime),
    ColumnType => "columnType", Wording::Reference(Sentence::LabelType),
    ColumnUser => "columnUser", Wording::Reference(Sentence::LabelUser),
    KeysApp => "keysApp", Wording::Own,
    KeysCreate => "keysCreate", Wording::Reference(Sentence::Create),
    ConfirmInstallPackage => "confirmInstallPackage", Wording::Own,
    ConfirmAddRepository => "confirmAddRepository", Wording::Own,
    ConfirmRemoveRepository => "confirmRemoveRepository", Wording::Own,
    ConfirmDeleteDevice => "confirmDeleteDevice", Wording::Own,
    ConfirmDeleteOwnDevice => "confirmDeleteOwnDevice", Wording::Own,
    ConfirmRevokeKey => "confirmRevokeKey", Wording::Own,
    FailureWrotePackageInstall => "failureWrotePackageInstall", Wording::Own,
    FailureWrotePackageCancel => "failureWrotePackageCancel", Wording::Own,
    FailureWroteRepositoryAdd => "failureWroteRepositoryAdd", Wording::Own,
    FailureWroteRepositoryRemove => "failureWroteRepositoryRemove", Wording::Own,
    FailureWroteDeviceRename => "failureWroteDeviceRename", Wording::Own,
    FailureWroteDeviceDelete => "failureWroteDeviceDelete", Wording::Own,
    FailureWroteKeyCreate => "failureWroteKeyCreate", Wording::Own,
    FailureWroteKeyRevoke => "failureWroteKeyRevoke", Wording::Own,
    FailureOwnDeviceDeleted => "failureOwnDeviceDeleted", Wording::Own,
    FailureDemoted => "failureDemoted", Wording::Own,
    TunersTitle => "tunersTitle", Wording::Reference(Sentence::HeaderTuners),
    TunersAdd => "tunersAdd", Wording::Reference(Sentence::Add),
    TunersDelete => "tunersDelete", Wording::Reference(Sentence::Delete),
    TunersDiscover => "tunersDiscover", Wording::Own,
    TunersReset => "tunersReset", Wording::Reference(Sentence::Reset),
    TunersUrl => "tunersUrl", Wording::Own,
    ProvidersTitle => "providersTitle", Wording::Own,
    ProvidersSchedulesDirect => "providersSchedulesDirect", Wording::Own,
    ProvidersXmltv => "providersXmltv", Wording::Own,
    ProvidersUsername => "providersUsername", Wording::Reference(Sentence::LabelUsername),
    ProvidersPassword => "providersPassword", Wording::Reference(Sentence::LabelPassword),
    ProvidersPostcode => "providersPostcode", Wording::Own,
    ProvidersLineup => "providersLineup", Wording::Own,
    ProvidersPath => "providersPath", Wording::Reference(Sentence::LabelPath),
    ProvidersAdd => "providersAdd", Wording::Reference(Sentence::Add),
    ProvidersDelete => "providersDelete", Wording::Reference(Sentence::Delete),
    MappingTitle => "mappingTitle", Wording::Own,
    DvrTitle => "dvrTitle", Wording::Reference(Sentence::HeaderDVR),
    DvrRecordingPath => "dvrRecordingPath", Wording::Reference(Sentence::LabelRecordingPath),
    DvrRecordingPathHelp => "dvrRecordingPathHelp", Wording::Reference(Sentence::LabelRecordingPathHelp),
    DvrMovieRecordingPath => "dvrMovieRecordingPath", Wording::Reference(Sentence::LabelMovieRecordingPath),
    DvrSeriesRecordingPath => "dvrSeriesRecordingPath", Wording::Reference(Sentence::LabelSeriesRecordingPath),
    DvrDefaults => "dvrDefaults", Wording::Reference(Sentence::HeaderDefaultRecordingSettings),
    DvrStartWhenPossible => "dvrStartWhenPossible", Wording::Reference(Sentence::LabelStartWhenPossible),
    DvrMinutesBefore => "dvrMinutesBefore", Wording::Reference(Sentence::MinutesBefore),
    DvrStopWhenPossible => "dvrStopWhenPossible", Wording::Reference(Sentence::LabelStopWhenPossible),
    DvrMinutesAfter => "dvrMinutesAfter", Wording::Reference(Sentence::MinutesAfter),
    ConfirmDeleteTuner => "confirmDeleteTuner", Wording::Own,
    ConfirmDeleteProvider => "confirmDeleteProvider", Wording::Own,
    FailureWroteTunerAdd => "failureWroteTunerAdd", Wording::Own,
    FailureWroteTunerDelete => "failureWroteTunerDelete", Wording::Own,
    FailureWroteTunerReset => "failureWroteTunerReset", Wording::Own,
    FailureWroteProviderAdd => "failureWroteProviderAdd", Wording::Own,
    FailureWroteProviderDelete => "failureWroteProviderDelete", Wording::Own,
    FailureWroteChannelMapping => "failureWroteChannelMapping", Wording::Own,
    FailureWroteDvr => "failureWroteDvr", Wording::Own,
    DetailRefreshMetadata => "detailRefreshMetadata", Wording::Reference(Sentence::RefreshMetadata),
    DetailRefreshReplace => "detailRefreshReplace", Wording::Own,
    DetailRefreshScanMode => "detailRefreshScanMode", Wording::Reference(Sentence::ScanForNewAndUpdatedFiles),
    FailureWroteRefreshItem => "failureWroteRefreshItem", Wording::Own,
    FailureAdministratorRestarted => "failureAdministratorRestarted", Wording::Own,
    FailureAdministratorShutDown => "failureAdministratorShutDown", Wording::Own,
    ServerSaid => "serverSaid", Wording::Own,
    FailureBodyTooLarge => "failureBodyTooLarge", Wording::Own,
    FailureBodyOverCap => "failureBodyOverCap", Wording::Own,
    FailureBridgeVerb => "failureBridgeVerb", Wording::Own,
    FailurePageNotListed => "failurePageNotListed", Wording::Own,
    FailurePageNotRewritable => "failurePageNotRewritable", Wording::Own,
    FailurePageTooLarge => "failurePageTooLarge", Wording::Own,
    DashboardReadOnly => "dashboardReadOnly", Wording::Own,
    FailureTimerRefused => "failureTimerRefused", Wording::Own,
    FailureSeriesTimerRefused => "failureSeriesTimerRefused", Wording::Own,
    FailureChannelInGroup => "failureChannelInGroup", Wording::Own,
    FailureActivityDate => "failureActivityDate", Wording::Own,
    FailureChapterIndex => "failureChapterIndex", Wording::Own,
    FailureOverlayMount => "failureOverlayMount", Wording::Own,
    FailureRange => "failureRange", Wording::Own,
    FailureYear => "failureYear", Wording::Own,
}

const TABLE_SOURCE: &str = include_str!("../strings/en-us.json");

/// The keys the boot shell reads straight from the table, which no variant
/// names: the shell runs before the wasm module exists.
#[cfg(test)]
const BOOT_KEYS: &[&str] = &["bootLoading", "bootWasmFailed", "bootRetry"];

/// Every key in the order the table writes it, which the parsed map does not
/// carry.
#[cfg(test)]
fn written() -> Vec<&'static str> {
    TABLE_SOURCE
        .lines()
        .filter_map(|line| line.trim_start().strip_prefix('"'))
        .filter_map(|line| line.split_once("\":"))
        .map(|(key, _)| key)
        .collect()
}

fn table() -> &'static serde_json::Map<String, serde_json::Value> {
    static TABLE: OnceLock<serde_json::Map<String, serde_json::Value>> = OnceLock::new();
    TABLE.get_or_init(|| {
        crate::failure::unraised::decoded(TABLE_SOURCE)
            .expect("strings/en-us.json is not a JSON object")
    })
}

/// The sentence `key` reads as; a key the table lacks reads as its own name,
/// which the gate is what prevents.
pub fn lookup(key: Text) -> &'static str {
    table()
        .get(key.key())
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| key.key())
}

pub fn format(key: Text, args: &[&str]) -> String {
    let template = lookup(key);
    let mut out = String::with_capacity(template.len());
    let mut rest = template;
    while let Some(open) = rest.find('{') {
        let Some(close) = rest[open..].find('}').map(|i| open + i) else {
            break;
        };
        let Ok(index) = rest[open + 1..close].parse::<usize>() else {
            out.push_str(&rest[..close + 1]);
            rest = &rest[close + 1..];
            continue;
        };
        out.push_str(&rest[..open]);
        out.push_str(args.get(index).copied().unwrap_or_default());
        rest = &rest[close + 1..];
    }
    out.push_str(rest);
    out
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use wasm_bindgen_test::wasm_bindgen_test;

    use super::{BOOT_KEYS, Text, Wording, written};

    /// The table lists the boot shell's keys, then every variant's key in the
    /// order `text!` declares them, and nothing else.
    #[wasm_bindgen_test]
    fn the_table_holds_every_variant_in_declaration_order() {
        let expected: Vec<&str> = BOOT_KEYS
            .iter()
            .copied()
            .chain(Text::ALL.iter().map(|text| text.key()))
            .collect();
        let held = written();
        let named: HashSet<&str> = expected.iter().copied().collect();
        let carried: HashSet<&str> = held.iter().copied().collect();
        let mut missing: Vec<&str> = named.difference(&carried).copied().collect();
        let mut stray: Vec<&str> = carried.difference(&named).copied().collect();
        missing.sort_unstable();
        stray.sort_unstable();
        assert!(
            missing.is_empty() && stray.is_empty(),
            "the string table lacks {missing:?} and holds {stray:?} under no variant"
        );
        let misplaced = held
            .iter()
            .zip(&expected)
            .find(|(held, wanted)| held != wanted)
            .map(|(held, wanted)| format!("{held} stands where {wanted} belongs"));
        assert!(
            misplaced.is_none(),
            "the string table is out of declaration order: {misplaced:?}"
        );
    }

    /// A variant naming the reference's own key names it as the reference's own
    /// table spells it, which is what lets the key stand as a variant with no
    /// conversion between the two.
    #[wasm_bindgen_test]
    fn every_reference_key_is_spelled_as_the_reference_spells_it() {
        let held: Vec<String> = Text::ALL
            .iter()
            .filter_map(|text| match text.sentence() {
                Wording::Reference(key) => Some(format!("{key:?}")),
                Wording::Own => None,
            })
            .filter(|key| {
                !key.starts_with(|value: char| value.is_ascii_uppercase())
                    || !key.chars().all(|value| value.is_ascii_alphanumeric())
            })
            .collect();
        assert!(
            held.is_empty(),
            "keys the reference does not spell: {held:?}"
        );
    }
}
